### ISSUE TITLE
repeat_distance does not work with Stops

### ISSUE THREAD

**Issue by rwrx** [tangrams/tangram-es#2146] opened 2020-02-11 12:25 UTC
Hello, I am not quite sure but I think there is a bug in the element `repeat_distance` on Tangram-ES. When we applied `repeat_distance` on roads labels, it did not show repeated labels as we would expected. If the `repeat_distance` was set only with one number (e.g. `repeat_distance: 300px`), the labels were shown with this distance. But if we wanted to show different labels distances at different zooms (e.g. `repeat_distance: [[15, 30px], [18, 500px]]`), I think it did not set properly the distances.

**Comment by matteblair** [comment] 2020-02-25 00:40
Just realized that this is a duplicate of https://github.com/tangrams/tangram-es/issues/2079

**Closed by matteblair** 2020-02-25 00:40 UTC
