### ISSUE TITLE
 Android can we use multiple MapViews in an app 

### ISSUE THREAD

**Issue by nomizodiac** [tangrams/tangram-es#789] opened 2016-06-13 11:58 UTC
I have two separate activities having their own MapViews and their objects. And i have implemented same scene file in them. Now when i load first activity it loads the map successfully. But when i load second acitivty app get stuck/crashes or it do not load the second mapview in that activity. Can you please guide if we can use multiple MapViews in an app in two separate activities? I get following logcat when app crash/stuck 

```
06-13 16:55:06.012 27456-28615/com.tpl.tplmaps I/Adreno-ES20: <validate_vertex_attrib_state:60>: validate_vertex_attrib_state: No vertex attrib is enabled in a draw call!
06-13 16:55:09.578 27456-27619/com.tpl.tplmaps D/Tangram: TANGRAM tangram.cpp:154: resize: 1080 x 1536
06-13 16:55:09.580 27456-27619/com.tpl.tplmaps W/Adreno-ES20: <core_glBindVertexArrayOES:288>: GL_INVALID_OPERATION
06-13 16:55:09.595 27456-27619/com.tpl.tplmaps D/Tangram: TANGRAM tangram.cpp:154: resize: 1080 x 1536
06-13 16:55:09.612 27456-27456/com.tpl.tplmaps I/ActivityMain: onLocationChanged(): Location received by Provider <fused>, PRIORITY: PRIORITY_HIGH_ACCURACY, IsBetter = true
06-13 16:55:10.800 27456-27619/com.tpl.tplmaps D/Tangram: TANGRAM tangram.cpp:154: resize: 1080 x 1411
06-13 16:55:12.100 27456-27456/com.tpl.tplmaps E/libEGL: call to OpenGL ES API with no current context (logged once per thread)
06-13 16:55:12.152 27456-27619/com.tpl.tplmaps D/Tangram: TANGRAM tangram.cpp:154: resize: 1080 x 1536
                                                          
                                                          
                                                          --------- beginning of crash
06-13 16:55:14.210 27456-27619/com.tpl.tplmaps A/libc: Fatal signal 11 (SIGSEGV), code 1, fault addr 0x29d in tid 27619 (GLThread 2732)
06-13 16:55:16.928 29217-29217/com.tpl.tplmaps D/FirebaseApp: com.google.firebase.auth.FirebaseAuth is not linked. Skipping initialization.
06-13 16:55:16.935 29217-29217/com.tpl.tplmaps D/FirebaseApp: Initialized class com.google.firebase.iid.FirebaseInstanceId.
06-13 16:55:16.935 29217-29217/com.tpl.tplmaps D/FirebaseApp: com.google.firebase.crash.FirebaseCrash is not linked. Skipping initialization.
```

**Comment by blair1618** [comment] 2016-06-13 14:37
Multiple `MapView` instances in a single app is not supported right now. It's on the roadmap, I would estimate that it will be available within a month.

**Comment by blair1618** [comment] 2016-06-13 15:38
Closing as duplicate of #757.

**Closed by blair1618** 2016-06-13 15:38 UTC
