### ISSUE TITLE
setPosition with ease duration 0, should work as setPositionNow

### ISSUE THREAD

**Issue by tallytalwar** [tangrams/tangram-es#903] opened 2016-08-05 18:48 UTC
Currently if one tries to do a `setPosition(x, y, 0)`, condition on `Ease::finish` is `true` on the next `Map::Update` and `Ease::update` is never called.

Refer: https://github.com/tangrams/tangram-es/blob/master/core/src/util/ease.h#L32

**Comment by blair1618** [comment] 2016-08-05 20:09
Can't reproduce this problem so far - the logic in the `Ease` functions seems to correctly handle this case and run `update(dt)` at least once for all ease instances.

**Comment by blair1618** [comment] 2016-08-17 23:56
This seems to work correctly from both the OS X and Android demo apps, and the logic in the code covers this case. Closing until we have evidence of a bug.

**Closed by blair1618** 2016-08-17 23:56 UTC
Labels: bug
