### ISSUE TITLE
onSceneReady invoked asynchronously for sync method

### ISSUE THREAD

**Issue by sarahlensing** [tangrams/tangram-es#1703] opened 2017-10-18 20:07 UTC
**TO REPRODUCE THE ISSUE, FOLLOW THESE STEPS:**

- Run the Tangram sample app and put log statements or breakpoints to observe order of callbacks

**RESULT:**

- `map.loadSceneFile` completes
- map tap responders, zoom etc set
- `onSceneReady` callback is invoked

**EXPECTED RESULT:**

- `onSceneReady` callback is invoked
- `map.loadSceneFile` completes
- map tap responders, zoom etc set

**ENVIRONMENT:**

Tangram 0.8.1
Android 7.0

**OTHER:**

Possibly related to earlier issue: https://github.com/tangrams/tangram-es/issues/1699 though logs don't show async method getting explicitly used

**Comment by matteblair** [comment] 2017-10-18 22:39
Aha! Yes, it's clear why this happens. Before they complete, the synchronous scene loading calls post the `SceneLoadListener$onSceneReady` callbacks to the UI thread, meaning that they will still execute _after_ the original loading call is complete. This is definitely weird :\

The two options that come to mind are:

  1. Run the `onSceneReady` callback within the synchronous scene loading call. We can do this by rearranging some of the logic in `MapController`. 
  2. Don't run a `onSceneReady` callback at all for synchronous scene loading calls. One one hand, this seems much more rational than executing a callback for code that is entirely synchronous. On the other hand, this changes the role of a `SceneLoadListener` because it would only be listening for _asynchronous_ scene loads now. 

I'm not sure which of this is least weird or most practical. Maybe there are other options too?

**Comment by tallytalwar** [comment] 2017-10-18 22:42
Based on the discussion IRL and on slack with @sarahlensing and @msmollin, I would incline to "2", which is what I thought after I found the cause of this issue.

**Comment by tallytalwar** [comment] 2017-10-18 22:55
I know some might be thinking, but why have sync calls at all for scene loading? I had to say it loud in this case now!

**Comment by sarahlensing** [comment] 2017-10-18 23:04
What @tallytalwar says is true, I'd prefer no callback invoked for synchronous scene loads. Since the call should complete all the work it is expected to do by the time the method returns there isn't a need for a callback here. Updating documentation should be sufficient for communicating the change in behavior.

**Comment by msmollin** [comment] 2017-10-18 23:10
I am hesitant to say yes to remove all synchronous loading apis mostly because we don't know all the use cases. For mobile yes synchronous is generally considered less suitable. But I have discussed it (I think) for the Mapzen SDKs

**Comment by tallytalwar** [comment] 2017-11-21 00:27
Closing in favor of #1728

**Closed by tallytalwar** 2017-11-21 00:27 UTC
