### ISSUE TITLE
Odd rendering issue on Walkabout on iPod Touch at zoom level 0

### ISSUE THREAD

**Issue by msmollin** [tangrams/tangram-es#1638] opened 2017-09-06 20:03 UTC
**TO REPRODUCE THE ISSUE, FOLLOW THESE STEPS:**

- Loaded Mapzen iOS SDK sample app
- Switched to Walkabout

**RESULT:**
A line was drawn across the Northern Hemisphere

**EXPECTED RESULT:**

Ideally no line :) 
**ENVIRONMENT:**

 - What operating system and device did you produce this issue on?
iOS 10.2.1 on an iPod Touch
 - If you used a released version, what is the version number?
Tangram-es 0.8

Screenshot:
![screen shot 2017-09-05 at 9 49 49 am](https://user-images.githubusercontent.com/1163880/30132028-f7581a52-931c-11e7-85ae-dec7775ceb5f.png)

**Comment by matteblair** [comment] 2017-09-06 20:33
Reproducible in Tangram JS as well, so it's likely an issue with the data or the scene file: https://tangrams.github.io/walkabout-style/#1.270833333333329/-20.6/-6.3

**Comment by nvkelso** [comment] 2017-09-07 17:04
This is a duplicate of https://github.com/tilezen/vector-datasource/issues/1107.

**Closed by nvkelso** 2017-09-07 17:04 UTC
Labels: ios

**Comment by msmollin** [comment] 2017-09-07 18:56
@nvkelso is there anything we need to do on device to resolve this? or is this purely a data issue?

**Comment by nvkelso** [comment] 2017-09-07 20:12
I believe it's a data problem only (not device, not Tangram, not style, problem in vector data).
