### ISSUE TITLE
Map styles library created by other developers

### ISSUE THREAD

**Issue by rwrx** [tangrams/tangram-es#1316] opened 2017-02-23 19:22 UTC
I just wanted to ask whether there is some library of user's created map styles or if you are planning such library in order for developers to share their map styles.

**Comment by nvkelso** [comment] 2017-02-23 22:40
@rwrx neat idea! do you have any styles to share &/or highlight in such a library?

We've created a few basemap styles at Mapzen, you have preview them here:

- https://mapzen.com/products/maps/

**Comment by rwrx** [comment] 2017-02-23 22:46
Yes, I did know about Mapzen basemap styles. I was just wondering if there is some library with user created styles. Unfortunately I don't have any styles, but in a short time I want to create some simple styles.

**Comment by matteblair** [comment] 2019-02-12 22:04
Not a bug or feature for the Tangram ES engine. Closing!

**Closed by matteblair** 2019-02-12 22:04 UTC
