### ISSUE TITLE
Starting and finishing an MapView activity eventually causes crash

### ISSUE THREAD

**Issue by thmalm** [tangrams/tangram-es#1557] opened 2017-06-28 14:30 UTC
I made modifications to your demo app (i.e. tangram-es/platforms/android/) to test if opening and closing the MainActivity multiple times works without problem. 
Basically, I added another launcher activity with a button to open the existing MainActivity, then closing it by back button, repeat ...

Result is that app eventually crashes with:
ashmem_create_region failed for 'indirect ref table': Too many open files 

How long it takes to crash the app depends on how soon you finish the MainActivity by back press. Up to approx. 210 times if you wait for onViewComplete() before you finish the MainActivity. Yes, that last test was done with timer to open/close the activity =)

Loading and unloading the MapView should unload resources correctly, right?

Tested on Samsung S5 with Android 6.0.1

**Comment by matteblair** [comment] 2017-06-28 15:31
Can you provide more of the stack trace from the crash?

It's true that MapView should release its resources when finished, but we have not tested it to such extremes before :)

**Comment by thmalm** [comment] 2017-06-28 20:25
Sorry, what I did mean to ask with releasing resources was if the normal case for this library is to have a "single activity"-applications .... 

Log prints from one of the crashes:

id W/DisplayListCanvas: DisplayListCanvas is started on unbinded RenderNode (without mOwningView)
06-28 16:32:48.549 30217-30321/com.mapzen.tangram.android D/Tangram: DEBUG importer.cpp:92: Processing scene import Stack:
06-28 16:32:48.549 30217-30321/com.mapzen.tangram.android D/Tangram: DEBUG importer.cpp:305: Starting importing Scene: asset:///scene.yaml
06-28 16:32:48.549 30217-30217/com.mapzen.tangram.android I/Timeline: Timeline: Activity_idle id: android.os.BinderProxy@fcd8ad3 time:57749429
06-28 16:32:48.589 30217-30217/com.mapzen.tangram.android V/ActivityThread: updateVisibility : ActivityRecord{a47d03d token=android.os.BinderProxy@691e579 {com.mapzen.tangram.android/com.mapzen.tangram.android.LaunchActivity}} show : false
06-28 16:32:48.609 30217-30321/com.mapzen.tangram.android D/Tangram: WARNING sceneLoader.cpp:1788: Can't find data source touch for layer touch
06-28 16:32:48.619 30217-30321/com.mapzen.tangram.android D/Tangram: WARNING styleParam.cpp:278: Invalid font-size '1.2em'.
06-28 16:32:48.729 30217-13228/com.mapzen.tangram.android D/libEGL: eglInitialize EGLDisplay = 0x8faf24c4
06-28 16:32:48.759 30217-13228/com.mapzen.tangram.android D/Tangram: TANGRAM tangram.cpp:865: setup GL
06-28 16:32:48.759 30217-13228/com.mapzen.tangram.android W/Adreno-ES20: <core_glUseProgram:1557>: GL_INVALID_VALUE
06-28 16:32:48.759 30217-13228/com.mapzen.tangram.android D/Tangram: TANGRAM hardware.cpp:60: Driver supports map buffer: 0
06-28 16:32:48.759 30217-13228/com.mapzen.tangram.android D/Tangram: TANGRAM hardware.cpp:61: Driver supports vaos: 1
06-28 16:32:48.759 30217-13228/com.mapzen.tangram.android D/Tangram: TANGRAM hardware.cpp:62: Driver supports rgb8_rgba8: 1
06-28 16:32:48.759 30217-13228/com.mapzen.tangram.android D/Tangram: TANGRAM hardware.cpp:63: Driver supports NPOT texture: 0
06-28 16:32:48.759 30217-13228/com.mapzen.tangram.android D/Tangram: TANGRAM hardware.cpp:77: Hardware max texture size 4096
06-28 16:32:48.759 30217-13228/com.mapzen.tangram.android D/Tangram: TANGRAM hardware.cpp:78: Hardware max combined texture units 32
06-28 16:32:48.759 30217-13228/com.mapzen.tangram.android D/Tangram: TANGRAM tangram.cpp:324: resize: 1080 x 1608
06-28 16:32:48.949 30217-13230/com.mapzen.tangram.android D/Tangram: TANGRAM tileWorker.cpp:51: Passed new TileBuilder to TileWorker
06-28 16:32:48.959 30217-13231/com.mapzen.tangram.android D/Tangram: TANGRAM tileWorker.cpp:51: Passed new TileBuilder to TileWorker
06-28 16:32:48.969 30217-13254/com.mapzen.tangram.android W/System.err: remove failed: ENOENT (No such file or directory) : /storage/emulated/0/Android/data/com.mapzen.tangram.android/cache/tile_cache/journal.tmp
06-28 16:32:48.969 30217-13228/com.mapzen.tangram.android W/Adreno-GSL: <gsl_ldd_control:475>: ioctl fd 26 code 0xc0140933 (IOCTL_KGSL_TIMESTAMP_EVENT) failed: errno 24 Too many open files
06-28 16:32:48.969 30217-13228/com.mapzen.tangram.android W/Adreno-GSL: <ioctl_kgsl_syncobj_create:2979>: (1b, c, 91) fail 24 Too many open files
06-28 16:32:48.969 30217-13228/com.mapzen.tangram.android W/Adreno-EGLSUB: <SwapBuffers:1339>: gsl_device_3d_add_fence_event failed
06-28 16:32:48.969 30217-13228/com.mapzen.tangram.android W/Adreno-EGL: <qeglDrvAPI_eglSwapBuffers:3904>: EGL_BAD_SURFACE
06-28 16:32:48.969 30217-13228/com.mapzen.tangram.android E/Surface: queueBuffer: error queuing buffer to SurfaceTexture, -22
06-28 16:32:48.969 30217-13228/com.mapzen.tangram.android W/Adreno-EGLSUB: <SwapBuffers:1345>: failed to queueBuffer
06-28 16:32:48.969 30217-13228/com.mapzen.tangram.android W/Adreno-EGL: <qeglDrvAPI_eglSwapBuffers:3904>: EGL_BAD_SURFACE
06-28 16:32:48.979 30217-13231/com.mapzen.tangram.android E/art: ashmem_create_region failed for 'indirect ref table': Too many open files
06-28 16:32:48.979 30217-13254/com.mapzen.tangram.android W/art: Large object allocation failed: ashmem_create_region failed for 'large object space allocation': Too many open files
06-28 16:32:48.979 30217-13228/com.mapzen.tangram.android E/Surface: queueBuffer: error queuing buffer to SurfaceTexture, -22
06-28 16:32:48.979 30217-13228/com.mapzen.tangram.android W/Adreno-EGLSUB: <SwapBuffers:1345>: failed to queueBuffer
06-28 16:32:48.979 30217-13228/com.mapzen.tangram.android W/Adreno-EGL: <qeglDrvAPI_eglSwapBuffers:3904>: EGL_BAD_SURFACE
06-28 16:32:48.979 30217-13254/com.mapzen.tangram.android I/art: Starting a blocking GC Alloc
06-28 16:32:48.979 30217-13254/com.mapzen.tangram.android I/art: Starting a blocking GC Alloc
06-28 16:32:49.009 30217-13228/com.mapzen.tangram.android E/Surface: queueBuffer: error queuing buffer to SurfaceTexture, -22
06-28 16:32:49.009 30217-13228/com.mapzen.tangram.android W/Adreno-EGLSUB: <SwapBuffers:1345>: failed to queueBuffer
06-28 16:32:49.009 30217-13228/com.mapzen.tangram.android W/Adreno-EGL: <qeglDrvAPI_eglSwapBuffers:3904>: EGL_BAD_SURFACE
06-28 16:32:49.009 30217-13257/com.mapzen.tangram.android E/NativeCrypto: AppData::create pipe(2) failed: Too many open files
06-28 16:32:49.019 30217-13255/com.mapzen.tangram.android E/NativeCrypto: AppData::create pipe(2) failed: Too many open files
06-28 16:32:49.029 30217-13255/com.mapzen.tangram.android E/Tangram: Failed url request: https://tile.mapzen.com/mapzen/vector/v1/all/16/19295/24642.mvt?api_key=<MAPZENKEY>& java.net.ConnectException: Failed to connect to tile.mapzen.com/151.101.193.95:443
06-28 16:32:49.029 30217-13256/com.mapzen.tangram.android E/NativeCrypto: AppData::create pipe(2) failed: Too many open files
06-28 16:32:49.049 30217-13256/com.mapzen.tangram.android E/NativeCrypto: AppData::create pipe(2) failed: Too many open files
06-28 16:32:49.049 30217-13256/com.mapzen.tangram.android E/Tangram: Failed url request: https://tile.mapzen.com/mapzen/vector/v1/all/16/19294/24641.mvt?api_key=<MAPZENKEY>& java.net.ConnectException: Failed to connect to tile.mapzen.com/151.101.193.95:443
06-28 16:32:49.059 30217-13257/com.mapzen.tangram.android W/art: Large object allocation failed: ashmem_create_region failed for 'large object space allocation': Too many open files
06-28 16:32:49.059 30217-13257/com.mapzen.tangram.android I/art: Waiting for a blocking GC Alloc

**Comment by matteblair** [comment] 2017-06-28 22:25
Most applications using Tangram ES only have one or a few Activities, as far as I know, but we haven't intentionally limited it to that use case.

Have you reproduced this same crash with multiple devices?

One thing to try, just to narrow down the cause, would be to use an `HttpHandler` with no cache directory. Trying to open all of the cached HTTP responses may be contributing to this resource exhaustion.

**Comment by thmalm** [comment] 2017-06-29 08:41
Nope, using a HttpHandler without cache doesn't really seem to affect the problem in a noticeable way. But you are probably right that the actual loading of data accelerates the problem.

I did a test to avoid the crash by not using HTTP requests altogether by using a more or less empty scene file (that is without any external dependencies like fonts or tile providers). This holds back the crash for a loong time but I guess eventually it will end up with the same result. Just by looking at the memory allocation footprint one can see where things are headed ... 

I've also tested on a Samsung S8 with Android 7.0 with the same result, attached is a trace from that device ...

[tangram_samsung-s8.txt](https://github.com/tangrams/tangram-es/files/1111243/tangram_samsung-s8.txt)

**Comment by matteblair** [comment] 2017-06-29 15:32
I see, thanks for the new information.

I am not sure of the cause, this may be due to some resource being used and not freed in our JNI code. JNI sometimes has resource limits on surprising things, like local object references. 

If you have a sample app that you're using to test this behavior, can you share it? That would help us figure out what's going on more quickly.

**Comment by thmalm** [comment] 2017-07-04 12:03
Sure, I did a fork and added my timer based test for repeatedly opening and closing the existing implementation of MainActivity. https://github.com/thmalm/tangram-es

With the pushed timer settings it takes about 10 - 15 minutes before crash occurs on my Samsung S5 with Android 6.0. But playing with the timer delays will give you different scenarios ...

**Comment by matteblair** [comment] 2019-02-12 23:00
We've fixed up some bugs in our JNI reference management on Android, I suspect this issue may be resolved. Gonna close this issue for now, please re-open if you're still encountering the problem!

**Closed by matteblair** 2019-02-12 23:00 UTC
