### ISSUE TITLE
Sometimes all text/fonts in android application disappears

### ISSUE THREAD

**Issue by hak-tpl** [tangrams/tangram-es#792] opened 2016-06-15 06:14 UTC
Hello!

I've been using Tangram in my own application and I'm facing a weird issue which appears often in the application. All text/fonts disappears in the whole application. At first I thought its an issue with my app but the same issue also appears on EraserMap 0.9.3-SNAPSHOT. 

**Screenshot:**  
![screenshot_2016-06-15-10-25-39](https://cloud.githubusercontent.com/assets/18065145/16069640/6fc2a0c4-32e9-11e6-91fc-5a9e199e398a.png)

**A screnshot from My app:**
![screenshot_2016-06-15-09-59-58](https://cloud.githubusercontent.com/assets/18065145/16069733/2d4bb4aa-32ea-11e6-86f1-950c12b92a5c.png)

**The Device I'm using is:**
Samsung Galaxy S3 
GT-I93000
Android OS version: 4.3

**Comment by karimnaaji** [comment] 2016-06-15 14:11
Hi @hak-tpl , we fixed a similar issue for phones running android OS before 5.0 (issue https://github.com/tangrams/tangram-es/issues/744)
Can you let me know which tangram snapshot version you're currently using?

**Comment by hak-tpl** [comment] 2016-06-16 04:47
@karimnaaji 

I'm using Tangram 0.3.2. Also im not talking about POIs' labels/fonts. The issue im facing is dsappearance of all TextViews text in the application. 

Kindly compare these two screenshots so that you can have a better idea of this issue

![screenshot_2016-06-16-09-41-37](https://cloud.githubusercontent.com/assets/18065145/16105764/55b6140e-33a7-11e6-89b4-1aae79cd3c68.jpeg)

![screenshot_2016-06-15-10-25-39](https://cloud.githubusercontent.com/assets/18065145/16105728/d3c9a44c-33a6-11e6-9f7d-76e01cc5c794.png)

**Comment by karimnaaji** [comment] 2016-06-16 19:28
I couldn't reproduce on a Galaxy S3 running Android 4.0.4. 
Could you give some steps to reproduce this issue, or maybe you noticed that right after launching the app?

**Comment by karimnaaji** [comment] 2016-06-16 20:08
We have a similar issue you can track on the android sdk https://github.com/mapzen/android/issues/121.

**Comment by hak-tpl** [comment] 2016-07-25 07:28
any update regarding this issue?

**Comment by matteblair** [comment] 2019-02-11 18:30
Closing in favor of more recent bug report in https://github.com/tangrams/tangram-es/issues/873

**Closed by matteblair** 2019-02-11 18:30 UTC
