### ISSUE TITLE
Compilation error with glm

### ISSUE THREAD

**Issue by quenlenliu** [tangrams/tangram-es#2192] opened 2020-10-11 08:19 UTC
Import project into clion
Compile it.

**RESULT:**

/tangram-es/core/deps/glm/glm/detail/type_vec4_simd.inl:156:11: error: ‘struct glm::tvec4<float, (glm::precision)5>’ has no member named ‘data’
    Result.data = _mm_mul_ps(a.data, _mm_rcp_ps(b.data));

**EXPECTED RESULT:**

Compile success

**ENVIRONMENT:**

ubuntu 18.04-lts

**Comment by matteblair** [comment] 2020-10-11 19:15
Hi, can you provide a few more bits of information?
- What compiler and version are you using?
- What versions of CLion and CMake are you using?
- What is the full compiler output for the error? (including the full compile command, if possible)

Our automated CI builds for Linux use a Ubuntu 18.04 image, so you also might be able to figure out your issue by comparing with those builds (https://app.circleci.com/pipelines/github/tangrams/tangram-es)

**Comment by matteblair** [comment] 2020-11-19 19:36
Duplicate of https://github.com/tangrams/tangram-es/issues/2209

**Closed by matteblair** 2020-11-19 19:36 UTC
