### ISSUE TITLE
Android: MapView GLSurfaceView is not visible on some Android configurations

### ISSUE THREAD

**Issue by terenn** [tangrams/tangram-es#788] opened 2016-06-13 08:40 UTC
Hello,

We're trying to use Tangram in our app; however, there seems to be a problem with Android 6.0 (and probably 5.0-5.1) on some devices.

Here is a picture of what happens: http://i.imgur.com/ewv2l0t.png
The blue box on the bottom should have been the map.

Another interesting thing is that when you return to the app after you pause it you can see the map blink and then disappear: https://gfycat.com/SizzlingPleasingCanine

This issue can be fixed by writing subclass of MapView and doing glSurfaceView.setZOrderOnTop(true) in configureGLSurfaceView(). This, however, prevents you from drawing any other views over the map, which is a must-have for us.

I have tested different configurations and this problem seems to occur on some of them:
- Nexus 5 with Android 6.0.1 (with 1 June patches)
- Sony Xperia Z5C with Android 6.0.1
- Android emulators with 5.1, 6.0 and N preview

It doesn't occur on:
- Samsung Galaxy S7 with Android 6.0.1
- Motorola Moto E with Android 4.4
- Android emulators with 4.4

**Comment by blair1618** [comment] 2016-06-13 15:09
Hey @terenn, thanks for the detailed report! It is definitely possible to layer supplementary Views on top of a MapView, this is done in [Mapzen's Android SDK](https://github.com/mapzen/android) (in the layout file [here](https://github.com/mapzen/android/blob/master/library/src/main/res/layout/mz_view_map.xml)). My first thought here would be to check the order of View entries in your layout, since Android generally draws views in the order they're written in the layout file. I'm not sure that layout order is the real problem though, because a problem like that *should* behave the same across different Android versions and devices.

**Comment by terenn** [comment] 2016-06-13 17:00
@blair1618 Yeah, that was my first thought too. But I can't seem to find any layer order problems. Also, a Google Map lived in the same spot perfectly well. It seems that it might be something that was changed in 5.0 that is affecting the composition.

**Comment by blair1618** [comment] 2016-06-13 17:57
If this were due to a change in Android 5.0 wouldn't that cause the problem to appear on your Galaxy S7 running 6.0.1?

Have you tried using the `MapView` or `MapFragment` from the Mapzen Android SDK ([docs](https://github.com/mapzen/android/blob/master/docs/getting-started.md))?

**Comment by terenn** [comment] 2016-06-14 09:33
@blair1618 Perhaps Samsung did something with thei OpenGL stack/compositor.

I haven't tested the Mapzen SDK because it immediately threw us over the 64K method limit.
I managed to work around the setZOrderOnTop limitations for now, because we were in a hurry to have the maps working.

I have to do other things for now, but if this bug is not fixed in the future, I will try the SDK when I can and report my findings here.

**Comment by blair1618** [comment] 2016-06-14 14:50
Very interesting, I'd like to get to the bottom of this. If you have a reproducible test case you can share that would be fantastic, but I understand if you're too busy.

**Comment by matteblair** [comment] 2019-02-11 18:31
Closing due to lack of further bug reports.

**Closed by matteblair** 2019-02-11 18:31 UTC
Labels: android
