### ISSUE TITLE
YAML reading error

### ISSUE THREAD

**Issue by MajidBashir** [tangrams/tangram-es#751] opened 2016-05-24 13:04 UTC
Application was working fine for me till yesterday, but when i updated, project is not working with that YAML file.
I did check only the scene.yaml file is working. 
I want to know what is the change made that has lead to an unknown error.
Application starts. Launch screen comes, remaining on that screen after a few seconds, it gives a popup 
LOST connection to device.
So it will be really helpful to get knowledge about that new change..

**Comment by tallytalwar** [comment] 2016-05-24 13:21
Hey @MajidBashir 

Can you post device logs for us to look more into this? And if possible, it will be helpful for us to look at your yaml scene file to track this issue down.

Thanks

**Comment by MajidBashir** [comment] 2016-05-24 13:24
`ERROR texture.cpp:75: Decoding image from memory failed`

**Comment by MajidBashir** [comment] 2016-05-24 13:25
Nothing More than this..

**Comment by tallytalwar** [comment] 2016-05-24 13:32
Can you send us the yaml scene file you are using? You can email it to any of the developers or `graphics@mapzen.com`.

**Comment by westnordost** [comment] 2016-06-09 22:54
I might have a related problem. My Android API 19 started to just end the map app (not crashing, it just closed itself immediately and the debugger lost the connection) just after OnMapReadyCallback was called. When I set a breakpoint into the callback, the callback would execute fine, but after that the app would end itself. The only log I get is
`868-1341/system_process I/ActivityManager: Process de.westnordost.osmagent (pid 17425) has died.
868-880/system_process I/WindowState: WIN DEATH: Window{4281f3b8 u0 de.westnordost.osmagent/de.westnordost.osmagent.MainActivity}
868-1341/system_process W/ActivityManager: Force removing Acti

vityRecord{42bb09d8 u0 de.westnordost.osmagent/.MainActivity t58}: app died, no saved state
868-880/system_process W/WindowManager: Force-removing child win Window{41aeaf98 u0 SurfaceView} from container Window{4281f3b8 u0 de.westnordost.osmagent/de.westnordost.osmagent.MainActivity}
868-3005/system_process I/ActivityManager: Force stopping de.westnordost.osmagent appid=10094 user=0: from pid 17499`

Though, on a API 23 it works just fine.

Anyway, since you are looking for clues for this bug, here is my current scene (without api key)
[scene.txt](https://github.com/tangrams/tangram-es/files/308039/scene.txt)

**Comment by blair1618** [comment] 2016-06-09 23:17
@westnordost It's difficult to guess exactly what the problem is there without seeing the rest of the app's code. If there's no stack trace from a Java exception or a native crash then I wouldn't assume that the problem is caused by tangram. You could try updating to version 0.3.1 of the tangram android SDK, which was just published to Maven Central yesterday, but that won't necessarily help diagnose your problem.

**Comment by tallytalwar** [comment] 2016-09-15 14:17
@MajidBashir @westnordost still seeing this issue? I am going to close this issue, since its been a while. Kindly open a new issue with more logging information and scene yaml if you are still facing this issue.

Thanks

**Closed by tallytalwar** 2016-09-15 14:17 UTC
