### ISSUE TITLE
how can i use offline .mvt data in Linux

### ISSUE THREAD

**Issue by TGISer** [tangrams/tangram-es#801] opened 2016-06-21 15:24 UTC
for example my local url is :

/home/tgiser/tiles/{z}/{x}/{y}.mvt

how can i use it.

thank you for your help!

**Comment by blair1618** [comment] 2016-06-21 22:42
Try creating a data source in your scene file like this:
```yaml
sources:
  local-tiles:
    type: MVT
    url: file:///home/tgiser/tiles/{z}/{x}/{y}.mvt
```
Let me know how it goes!

**Comment by TGISer** [comment] 2016-06-22 00:22
@blair1618 

no error but no map shows.

**Comment by karimnaaji** [comment] 2016-10-20 15:48
Initial work using `MBTiles` has been done here by @hallahan https://github.com/tangrams/tangram-es/pull/982.

**Comment by matteblair** [comment] 2019-02-11 18:33
I believe local directory tile sources are working as intended. Closing!

**Closed by matteblair** 2019-02-11 18:33 UTC
