### ISSUE TITLE
iOS crash

### ISSUE THREAD

**Issue by Tahlia-rt** [tangrams/tangram-es#1533] opened 2017-06-09 08:29 UTC
**TO REPRODUCE THE ISSUE, FOLLOW THESE STEPS:**

First of all,
I am sorry not to be able to write more because this crash got from Fabric.
(also no information of user)
It is a first question to me, so if the information needs to be suggested more , please don't hesitate to advise with it.

**RESULT:**

Describe the result here.

**EXPECTED RESULT:**
TangramMap	Tangram::Texture::update(Tangram::RenderState&, unsigned int, unsigned int const*) + 424
TangramMap	Tangram::FontContext::updateTextures(Tangram::RenderState&) + 84
TangramMap	Tangram::TextStyle::onBeginFrame(Tangram::RenderState&) + 32
TangramMap	Tangram::Map::render() + 808
TangramMap	_hidden#139_ + 30676

TangramMap	 Tangram::TileWorker::run(Tangram::TileWorker::Worker*) + 116
TangramMap	void* std::__1::__thread_proxy<std::__1::tuple<void (Tangram::TileWorker::*)(Tangram::TileWorker::Worker*), Tangram::TileWorker*, Tangram::TileWorker::Worker*> >(void*) + 116

TangramMap	Tangram::TileWorker::run(Tangram::TileWorker::Worker*) + 116
TangramMap	void* std::__1::__thread_proxy<std::__1::tuple<void (Tangram::TileWorker::*)(Tangram::TileWorker::Worker*), Tangram::TileWorker*, Tangram::TileWorker::Worker*> >(void*) + 116
**ENVIRONMENT:**

Tangram 0.6.2 (not included newer)
iOS 10.3.2 
iPhone 6

**OTHER:**

Thank you!

**Comment by matteblair** [comment] 2017-06-09 15:58
Hi @Tahlia-rt, thanks for the report. Are you able to try using newer versions of Tangram in your app? The newest version available on Cocoapods is 0.7.1 (https://cocoapods.org/pods/Tangram-es) and it's possible this issue has already been fixed in one of the updates since 0.4.6

**Comment by Tahlia-rt** [comment] 2017-06-10 17:49
@matteblair okay thanks for your quick reply :)

**Comment by tallytalwar** [comment] 2017-06-15 16:00
Closing, please reopen or file a new issue if still reproducible with a newer version of tangram.

Thanks

**Closed by tallytalwar** 2017-06-15 16:00 UTC
