### ISSUE TITLE
how to implement text and sprite(icon) mix show

### ISSUE THREAD

**Issue by czxczq521** [tangrams/tangram-es#895] opened 2016-08-03 08:28 UTC
I wang to implement text and sprite(icon) mix show label, order of text and sprite  how to process.  
Such as: 
![image](https://cloud.githubusercontent.com/assets/16661939/17358837/7bb987d4-5996-11e6-95d9-b35f5f11caf1.png)

**Comment by czxczq521** [comment] 2016-08-03 08:32
Such as:

**Comment by czxczq521** [comment] 2016-08-03 08:32
Such as:

**Comment by czxczq521** [comment] 2016-08-03 08:32
![image](https://cloud.githubusercontent.com/assets/16661939/17359143/d86b50b0-5997-11e6-9208-f03887c8bd3a.png)

**Comment by czxczq521** [comment] 2016-08-03 08:33
![image](https://cloud.githubusercontent.com/assets/16661939/17359175/00f1f0c0-5998-11e6-89da-c2cba37b5de4.png)

**Comment by blair1618** [comment] 2016-08-03 16:31
If you are trying to add text to a feature drawn with a 'points' style, check the documentation for the 'text' parameter of the 'points' style here: https://mapzen.com/documentation/tangram/draw/#text. You can add text to a point and change its offset, font properties, etc.

Let me know if I have misunderstood or if you have more questions.

**Comment by nvkelso** [comment] 2016-08-03 16:48
Is this sort of "info bubble" usually handled as the UX level outside of Tangram?

**Comment by czxczq521** [comment] 2016-08-04 02:08
Thanks. I try to add text to a feature drawn with a 'points' style. It can show, but has a question occurring, the texts  show order is error, it shows on another sprite icon. Such as:

**Comment by czxczq521** [comment] 2016-08-04 02:09
![image](https://cloud.githubusercontent.com/assets/16661939/17388003/75a447a4-5a2b-11e6-99b0-8795f1656a04.png)

**Comment by czxczq521** [comment] 2016-08-04 02:11
I am trying to let info bubble show on tangram map,  Don't handle as the UK level.

**Comment by matteblair** [comment] 2019-02-11 23:52
Looks like this issue got abandoned - sorry about that. Unfortunately, the overlapping labels you see is the expected behavior. I can think of two approaches to resolving this:
1. Configure these labels with collision priority, so that they do not overlap (this is the strategy we use for basemaps)
2. Use the UI utilities of your target platform (Android or iOS) to generate an image of the entire label, including text, and then use that as the sprite for these points.

I'm closing this issue due to its age, but can re-open if needed.

**Closed by matteblair** 2019-02-11 23:52 UTC
