### ISSUE TITLE
Cannot load files specified with relative paths

### ISSUE THREAD

**Issue by westnordost** [tangrams/tangram-es#1059] opened 2016-11-03 11:37 UTC
I was trying to load the Tron 2.0 style (unbundled) on Android and got a bunch of errors. The root problem here seems to be that Tangram is unable to find files that are referenced in paths that include `../`, like they can be found plentiful in the Tron style when blocks, images etc. are imported.

Tangram then reports the error:

```
D/Tangram: Failed to open asset at path: tron/styles/../blocks/geometry/normal.yaml
```

I am guessing the problem is, that any paths specified in a scene file (be it `import` or a texture definition) are interpreted by Tangram-JS as relative to the file the statement is written while Tangram-ES interprets the paths as relative to the main scene file.
If my assumption is correct, then any "modern" style that organizes its components into several folders rather than put everything in one scene.yaml will not work on Tangram-ES.

**Comment by blair1618** [comment] 2016-11-03 16:11
Yep! We're working on resolving this.

This kind of path actually works fine for the desktop and iOS builds of tangram-es, the problem is that on Android, the scene files are stored in the asset bundle (which is basically a zip archive) and accessed through `AssetManager`. `AssetManager` doesn't resolve any dot segments in file paths, so imports like your example end up failing to locate a file. 

The solution we'll apply is to treat all resource paths as URLs and normalize them in our code before making file/http requests.

**Comment by westnordost** [comment] 2016-11-03 20:12
Oh, Android...

Cool that you are already working on it!

**Comment by tallytalwar** [comment] 2016-12-09 16:01
[0.4.6-android](https://github.com/tangrams/tangram-es/releases/tag/0.4.6-android) should take care of this issue. Can you give this a try? Going to close this issue, if you still find similar issues please free to reopen this or open a new one.

Thanks

**Closed by tallytalwar** 2016-12-09 16:01 UTC
