### ISSUE TITLE
Building tangram-es with new android studio 2.2 with cmake support

### ISSUE THREAD

**Issue by FarazKhalidZaki** [tangrams/tangram-es#807] opened 2016-06-25 11:35 UTC
Android studio 2.2 (preview version) has been launched which supports external cmake builds. 
http://tools.android.com/tech-docs/external-c-builds
http://android-developers.blogspot.com/2016/05/android-studio-22-preview-new-ui.html
So I think it is possible now to build tangram-es inside android studio, please help me that how can I build and get access to native side of tangram-es inside android studio.

**Comment by blair1618** [comment] 2016-06-27 15:05
Hi Faraz,

You're correct! In theory, the CMake build support in Android Studio 2.2 should enable us to run native Android builds entirely from Android Studio. It's not clear from the release notes that the current releases support all the options that we'll need to use in CMake, but I can give it a try in a branch and let you know whether it works. We'll probably want to use this build process by default once this feature is in a stable release of Android Studio.

**Comment by FarazKhalidZaki** [comment] 2016-07-11 14:01
Hi @blair1618,
I have been trying to build tangram-es inside android studio 2.2 using cmake as externalNativeBuild support, and I am stuck. Below are the errors i got in android-studio, please review and help. I am using same cmakeLists.txt provided by you.
 
External Native Build Issues
Error while executing '/home/supporttech/Android/Sdk/cmake/bin/cmake' with arguments {-H/home/supporttech/tangramTest -B/home/supporttech/tangramTest/android/tangram/externalNativeBuild/cmake/debug/armeabi -GAndroid Gradle - Ninja -DANDROID_ABI=armeabi -DANDROID_NDK=/home/supporttech/Android/android-ndk-r10e -DCMAKE_LIBRARY_OUTPUT_DIRECTORY=/home/supporttech/tangramTest/android/tangram/build/intermediates/cmake/debug/obj/armeabi -DCMAKE_BUILD_TYPE=Debug -DCMAKE_MAKE_PROGRAM=/home/supporttech/Android/Sdk/cmake/bin/ninja -DCMAKE_TOOLCHAIN_FILE=/home/supporttech/Android/Sdk/cmake/android.toolchain.cmake -DANDROID_NATIVE_API_LEVEL=android-23}
-- Adjusting Android API level 'android-23' to 'android-21'
-- No target defined (give as parameter -DPLATFORM_TARGET=platform_name).
-- Targets available: darwin;ios;android;raspberrypi;linux.
-- Will use your OS: android.
-- Including android dependent cmake file : /home/supporttech/tangramTest/toolchains/android.cmake
-- Configuring incomplete, errors occurred!
See also "/home/supporttech/tangramTest/android/tangram/externalNativeBuild/cmake/debug/armeabi/CMakeFiles/CMakeOutput.log".
CMake Error at toolchains/android.cmake:4 (message):
  Provide ndk make, located in <NDK_ROOT>/prebuilt/<OS>/bin/,
  -DMAKE_BUILD_TOOL=<NDK_PREBUILT_BIN>/make
Call Stack (most recent call first):
  CMakeLists.txt:65 (include)
Error:executing external native build for cmake /home/supporttech/tangramTest/CMakeLists.txt
Error while executing '/home/supporttech/Android/Sdk/cmake/bin/cmake' with arguments {-H/home/supporttech/tangramTest -B/home/supporttech/tangramTest/android/tangram/externalNativeBuild/cmake/release/armeabi -GAndroid Gradle - Ninja -DANDROID_ABI=armeabi -DANDROID_NDK=/home/supporttech/Android/android-ndk-r10e -DCMAKE_LIBRARY_OUTPUT_DIRECTORY=/home/supporttech/tangramTest/android/tangram/build/intermediates/cmake/release/obj/armeabi -DCMAKE_BUILD_TYPE=Release -DCMAKE_MAKE_PROGRAM=/home/supporttech/Android/Sdk/cmake/bin/ninja -DCMAKE_TOOLCHAIN_FILE=/home/supporttech/Android/Sdk/cmake/android.toolchain.cmake -DANDROID_NATIVE_API_LEVEL=android-23}
-- Adjusting Android API level 'android-23' to 'android-21'
-- No target defined (give as parameter -DPLATFORM_TARGET=platform_name).
-- Targets available: darwin;ios;android;raspberrypi;linux.
-- Will use your OS: android.
-- Including android dependent cmake file : /home/supporttech/tangramTest/toolchains/android.cmake
-- Configuring incomplete, errors occurred!
See also "/home/supporttech/tangramTest/android/tangram/externalNativeBuild/cmake/release/armeabi/CMakeFiles/CMakeOutput.log".
CMake Error at toolchains/android.cmake:4 (message):
  Provide ndk make, located in <NDK_ROOT>/prebuilt/<OS>/bin/,
  -DMAKE_BUILD_TOOL=<NDK_PREBUILT_BIN>/make
Call Stack (most recent call first):
  CMakeLists.txt:65 (include)
Error:executing external native build for cmake /home/supporttech/tangramTest/CMakeLists.txt

**Comment by FarazKhalidZaki** [comment] 2016-07-13 07:23
Hi @blair1618 
I resolved those errors and now i am getting following errors:

Error:Execution failed for task ':tangram:externalNativeBuildRelease'.
> com.android.ide.common.process.ProcessException: Error while executing '/home/supporttech/Android/Sdk/cmake/bin/cmake' with arguments {--build /home/supporttech/tangramTest2/android/tangram/externalNativeBuild/cmake/release/armeabi --target alfons}
  ninja: error: build.ninja:488: bad $-escape (literal $ must be written as $$)
Error:error: build.ninja:488: bad $-escape (literal $ must be written as $$)

I didn't find any help on this.

**Comment by FarazKhalidZaki** [comment] 2016-07-13 08:37
After replacing $(MAKE) by $$(MAKE) in build.ninja file it starts building process but stops with the following error:
Error:Execution failed for task ':tangram:externalNativeBuildRelease'.
> com.android.ide.common.process.ProcessException: Error while executing '/home/supporttech/Android/Sdk/cmake/bin/cmake' with arguments {--build /home/supporttech/tangramTest2/android/tangram/externalNativeBuild/cmake/release/armeabi --target alfons}
  [1/207] Building C object external/alfons/deps/harfbuzz-icu-freetype/CMakeFiles/icucommon.dir/icu/common/ubidiwrt.c.o
  [2/207] Building C object external/alfons/deps/harfbuzz-icu-freetype/CMakeFiles/icucommon.dir/icu/common/ucnv_u7.c.o
  [3/207] Building C object external/alfons/deps/harfbuzz-icu-freetype/CMakeFiles/icucommon.dir/icu/common/ucnv_u8.c.o
  [4/207] Building C object external/alfons/deps/harfbuzz-icu-freetype/CMakeFiles/icucommon.dir/icu/common/ucnvdisp.c.o
  [5/207] Building C object external/alfons/deps/harfbuzz-icu-freetype/CMakeFiles/icucommon.dir/icu/common/ucnvhz.c.o
  [6/207] Building C object external/alfons/deps/harfbuzz-icu-freetype/CMakeFiles/icucommon.dir/icu/common/ucnvisci.c.o
  [7/207] Building C object external/alfons/deps/harfbuzz-icu-freetype/CMakeFiles/icucommon.dir/icu/common/ucnvlat1.c.o
  [8/207] Building CXX object external/alfons/deps/harfbuzz-icu-freetype/CMakeFiles/icucommon.dir/icu/common/ustrtrns.cpp.o
  FAILED: /home/supporttech/Android/android-ndk-r10e/toolchains/arm-linux-androideabi-4.9/prebuilt/linux-x86_64/bin/arm-linux-androideabi-gcc  -DANDROID -DPIC -DPLATFORM_ANDROID -DU_COMMON_IMPLEMENTATION -DU_STATIC_IMPLEMENTATION=1 -isystem /home/supporttech/Android/android-ndk-r10e/platforms/android-21/arch-arm/usr/include -isystem /home/supporttech/Android/android-ndk-r10e/sources/cxx-stl/gnu-libstdc++/4.9/include -isystem /home/supporttech/Android/android-ndk-r10e/sources/cxx-stl/gnu-libstdc++/4.9/libs/armeabi/include -isystem /home/supporttech/Android/android-ndk-r10e/sources/cxx-stl/gnu-libstdc++/4.9/include/backward -I../../../../../../external/alfons/deps/harfbuzz-icu-freetype/icu/common -I../../../../../../external/alfons/deps/harfbuzz-icu-freetype/icu/stubdata -I../../../../../../external/alfons/deps/harfbuzz-icu-freetype/icu/common/unicode -fexceptions -Wno-psabi --sysroot=/home/supporttech/Android/android-ndk-r10e/platforms/android-21/arch-arm -funwind-tables -finline-limit=64 -fsigned-char -no-canonical-prefixes -march=armv5te -mtune=xscale -msoft-float -fdata-sections -ffunction-sections -Wa,--noexecstack  -mthumb -fomit-frame-pointer -fno-strict-aliasing -O3 -DNDEBUG -fPIC -MMD -MT external/alfons/deps/harfbuzz-icu-freetype/CMakeFiles/icucommon.dir/icu/common/ubidiwrt.c.o -MF external/alfons/deps/harfbuzz-icu-freetype/CMakeFiles/icucommon.dir/icu/common/ubidiwrt.c.o.d -o external/alfons/deps/harfbuzz-icu-freetype/CMakeFiles/icucommon.dir/icu/common/ubidiwrt.c.o   -c /home/supporttech/tangramTest2/external/alfons/deps/harfbuzz-icu-freetype/icu/common/ubidiwrt.c
  /home/supporttech/tangramTest2/external/alfons/deps/harfbuzz-icu-freetype/icu/common/ubidiwrt.c: In function 'ubidi_writeReordered_52':
  /home/supporttech/tangramTest2/external/alfons/deps/harfbuzz-icu-freetype/icu/common/ubidiwrt.c:643:1: internal compiler error: in patch_jump_insn, at cfgrtl.c:1275
   }
   ^
  Please submit a full bug report,
  with preprocessed source if appropriate.
  See <http://source.android.com/source/report-bugs.html> for instructions.
  ninja: build stopped: subcommand failed.

Is it a problem with alfons submodule, or am I doing it wrong?

**Comment by blair1618** [comment] 2016-07-13 16:28
Hi @FarazKhalidZaki, you're venturing into new territory here! Do you have a fork of tangram-es with these changes so that I might see exactly what your code is doing? Do you know which Android Studio preview version you're using? It's hard to say exactly what the problem is without seeing the code. I can give more feedback once I find some time to try this process myself, but for now I have 2 thoughts:

1. Modifying the ninja file is probably not the right approach - those files are only intended to be written and read by programs.
2. The Android Studio CMake integration is definitely still a beta product, things might just be broken 😄

**Comment by FarazKhalidZaki** [comment] 2016-07-14 08:49
Hi @blair1618, you are right it's still a beta product. :)  
I am using android studio 2.2 preview 4 on ubuntu 14.04.1, NDK version I am using is r10e. Below is the build.gradle script I've used to build tangram-es with android-studio cmake support. 

```
android {
  compileSdkVersion 23

  buildToolsVersion "21.1.2"

  defaultConfig {
    minSdkVersion 15
    targetSdkVersion 23
    versionCode buildVersionCode()
    versionName VERSION_NAME
    cmake{
      abiFilters 'armeabi-v7a'
      arguments "-DCMAKE_TOOLCHAIN=/home/supporttech/Android/android-ndk-r10e/toolchains/arm-linux-androideabi-clang3.6",
                "-DMAKE_BUILD_TOOL=/home/supporttech/Android/android-ndk-r10e/prebuilt/linux-x86_64/bin/make", 
                "-DLIBRARY_OUTPUT_PATH_ROOT=/home/supporttech/tangram-es/android/tangram",
                "-DANDROID_STL=gnustl_static"
    }
  }
  externalNativeBuild {
    cmake {
      path "/home/supporttech/tangram-es/CMakeLists.txt"
    }
  }
  sourceSets.main {
    manifest.srcFile 'AndroidManifest.xml'
    java.srcDirs = ['src']
    jni.srcDirs = []
    jniLibs.srcDirs = ['libs']
  }
}
```

**Comment by FarazKhalidZaki** [comment] 2016-07-14 13:30
I think I messed up all the things :smile: 
I was facing many problem due to cmake cache. Now I've cleaned the project and made some changes in cmake arguments in build.gradle following the "MakeFile" provided with tangram-es.

```
cmake{
      abiFilters 'armeabi-v7a'
      arguments "-DPLATFORM_TARGET=android",
              "-DCMAKE_TOOLCHAIN_FILE=/home/supporttech/tangram-es11/toolchains/android.toolchain.cmake",
              "-DCMAKE_TOOLCHAIN_NAME=arm-linux-androideabi-clang3.6",
              "-DMAKE_BUILD_TOOL=/home/supporttech/Android/android-ndk-r10e/prebuilt/darwin-x86_64/bin/make",
              "-DANDROID_STL=c++_static",
              "-DLIBRARY_OUTPUT_PATH_ROOT=/home/supporttech/tangram-es11/android/tangram",
	          "-DCMAKE_EXPORT_COMPILE_COMMANDS=TRUE"
    }
```

Now I am getting this error:
  **The LOCATION property may not be read from target "tangram".  Use the
  target name directly with add_custom_command, or use the generator
CMake Error at toolchains/android.gdb.cmake:83 (get_property):
  expression $<TARGET_FILE>, as appropriate.**



Here is the log:
> External Native Build Issues
> Error while executing '/home/supporttech/Android/Sdk/cmake/bin/cmake' with arguments {-H/home/supporttech/tangram-es11 -B/home/supporttech/tangram-es11/android/tangram/externalNativeBuild/cmake/debug/armeabi-v7a -GAndroid Gradle - Ninja -DANDROID_ABI=armeabi-v7a -DANDROID_NDK=/home/supporttech/Android/android-ndk-r10e -DCMAKE_LIBRARY_OUTPUT_DIRECTORY=/home/supporttech/tangram-es11/android/tangram/build/intermediates/cmake/debug/obj/armeabi-v7a -DCMAKE_BUILD_TYPE=Debug -DCMAKE_MAKE_PROGRAM=/home/supporttech/Android/Sdk/cmake/bin/ninja -DCMAKE_TOOLCHAIN_FILE=/home/supporttech/Android/Sdk/cmake/android.toolchain.cmake -DANDROID_NATIVE_API_LEVEL=android-23 -DPLATFORM_TARGET=android -DCMAKE_TOOLCHAIN_FILE=/home/supporttech/tangram-es11/toolchains/android.toolchain.cmake -DCMAKE_TOOLCHAIN_NAME=arm-linux-androideabi-clang3.6 -DMAKE_BUILD_TOOL=/home/supporttech/Android/android-ndk-r10e/prebuilt/darwin-x86_64/bin/make -DANDROID_STL=c++_static -DLIBRARY_OUTPUT_PATH_ROOT=/home/supporttech/tangram-es11/android/tangram -DCMAKE_EXPORT_COMPILE_COMMANDS=TRUE}
> -- Adjusting Android API level 'android-23' to 'android-21'
> -- Platform chosen : ANDROID
> -- Including android dependent cmake file : /home/supporttech/tangram-es11/toolchains/android.cmake
> -- Will use make prebuilt tool located at : /home/supporttech/Android/android-ndk-r10e/prebuilt/darwin-x86_64/bin/make
> -- Performing Test FLAG_WEXTRA
> -- Performing Test FLAG_WEXTRA - Success
> -- Looking for GLM
> -- GLM include /home/supporttech/tangram-es11/external/../core/include/glm
> -- Creating directory /home/supporttech/tangram-es11/android/tangram/externalNativeBuild/cmake/debug/armeabi-v7a/external/alfons/deps/harfbuzz-icu-freetype/freetype-2.6/include/freetype/config
> -- Creating file /home/supporttech/tangram-es11/android/tangram/externalNativeBuild/cmake/debug/armeabi-v7a/external/alfons/deps/harfbuzz-icu-freetype/freetype-2.6/include/freetype/config/ftconfig.h
> -- Looking for unistd.h
> -- Looking for unistd.h - found
> -- Looking for fcntl.h
> -- Looking for fcntl.h - found
> -- Looking for stdint.h
> -- Looking for stdint.h - found
> -- Creating file /home/supporttech/tangram-es11/android/tangram/externalNativeBuild/cmake/debug/armeabi-v7a/external/alfons/deps/harfbuzz-icu-freetype/freetype-2.6/include/freetype/config/ftoption.h
> -- harfbuzzfreetypeicucommon
> -- ANDROID_LIB_DIR >>> /home/supporttech/tangram-es11/android/tangram
> -- TARGET_LOCATION >>> 
> -- Configuring incomplete, errors occurred!
> See also "/home/supporttech/tangram-es11/android/tangram/externalNativeBuild/cmake/debug/armeabi-v7a/CMakeFiles/CMakeOutput.log".
> CMake Error at toolchains/android.gdb.cmake:83 (get_property):
>   The LOCATION property may not be read from target "tangram".  Use the
>   target name directly with add_custom_command, or use the generator
>   expression $<TARGET_FILE>, as appropriate.
> Call Stack (most recent call first):
>   toolchains/android.cmake:63 (android_ndk_gdb_debuggable)
>   CMakeLists.txt:65 (include)
> Error:executing external native build for cmake /home/supporttech/tangram-es11/CMakeLists.txt

**Comment by karimnaaji** [comment] 2016-07-14 15:44
Can you try removing those line from your configuration and see how it goes?

https://github.com/tangrams/tangram-es/blob/master/toolchains/android.cmake#L33_L34

**Comment by FarazKhalidZaki** [comment] 2016-07-25 07:46
hi @blair1618 I think you are right "android-studio 2.2 is still a beta product" :smile: 
I got fed up with the unusual behavior of new android-studio 2.2 externalbuildTool :( . I think we should wait for stable release.
And one more thing, please tell me what IDE your team use for the development purpose of tangram-es. I want to contribute in rendering complex roof shapes and also shadow mapping. I have implemented custom roof shape rendering on tangram web, now i want to implement this functionality on tangram-es.
Here is an example.
![c1](https://cloud.githubusercontent.com/assets/19620016/17093897/e75fe926-5200-11e6-9200-98649d00979d.PNG)

**Comment by blair1618** [comment] 2016-07-25 15:27
Custom roof shapes are a very interesting domain, are you thinking of the roof shape tags in OSM? (http://taginfo.openstreetmap.org/keys/roof:shape#values)

CMake allows us to generate build files for many different IDEs and tools, so our team doesn't use a consistent build environment. Personally, I would say CLion works particularly well for our project, but I also use XCode and command line tools.

**Comment by FarazKhalidZaki** [comment] 2016-07-26 12:26
Thanks @blair1618 , I've setup the environment (CLion) on ubuntu and its working fine. :)

**Comment by blair1618** [comment] 2016-09-07 16:49
Combined CPP/Java Android builds in Gradle are now working in a branch: https://github.com/tangrams/tangram-es/tree/android-cmake. This currently requires installing Android Studio 2.2 RC 1 and updating the Android SDK to include 'ndk-bundle' and 'cmake'.

I would like to submit this as a PR but I'm unable to make these builds work on our CI server: https://travis-ci.org/tangrams/tangram-es/jobs/158072483

There doesn't yet seem to be a way to update the Android SDK to include 'ndk-bundle' and 'cmake' from command line - you have to go through the Android Studio GUI. Hopefully this will be corrected when Studio 2.2 is officially released and then we can make this our default build process.

**Comment by FarazKhalidZaki** [comment] 2016-09-10 09:13
Its giving me the same error with ninja.build files 
**Error:error: build.ninja:531: bad $-escape (literal $ must be written as $$)**

**Comment by blair1618** [comment] 2016-09-12 15:14
The 'android-cmake' branch has an updated version of the yaml-cpp submodule which includes a fix for that error (the guilty code is removed in this commit https://github.com/tangrams/yaml-cpp/commit/f287811d4db63f2247cb21a013ba1cc90a57eda8). Try updating your submodules.

**Comment by FarazKhalidZaki** [comment] 2016-09-20 10:22
Hi @blair1618 I am able to build tangram-es inside Android Studio, but there is a linking problem with libtangram.so. Here is the log:

09-20 15:16:39.944 14564-14564/com.mapzen.tangram.android E/AndroidRuntime: FATAL EXCEPTION: main
                                                                            Process: com.mapzen.tangram.android, PID: 14564
                                                                            java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/com.mapzen.tangram.android-2/base.apk"],nativeLibraryDirectories=[/data/app/com.mapzen.tangram.android-2/lib/arm, /vendor/lib, /system/lib]]] couldn't find "libtangram.so"

**Comment by blair1618** [comment] 2016-09-26 05:58
I see this behavior too when I try to run the Android build on a new machine. Not sure what the issue is. But Android Studio 2.2 is [released now](http://android-developers.blogspot.com/2016/09/android-studio-2-2.html)! So we'll definitely move forward with this build system change soon.

**Comment by tallytalwar** [comment] 2017-01-10 02:00
Resolved by https://github.com/tangrams/tangram-es/pull/1152

**Closed by tallytalwar** 2017-01-10 02:00 UTC
