### ISSUE TITLE
iOS: Label overlap

### ISSUE THREAD

**Issue by mjcunningham** [tangrams/tangram-es#831] opened 2016-07-13 16:05 UTC
Check out alphabet city.
On the iOS 10 beta.
![2016-07-13 12 01 13](https://cloud.githubusercontent.com/assets/307758/16810519/20faf79c-48f2-11e6-8e09-8ec6aa92e1b3.png)

**Comment by blair1618** [comment] 2016-07-13 16:32
NEAT. The engine probably thinks these labels are (or should be) aligned with the roads, which would make them not collide. I'll see if this can be reproduced in tangram-es master and we'll debug from there.

**Comment by tallytalwar** [comment] 2016-07-13 16:45
It will be good to look at the debug label bounding boxes here. @karimnaaji and I were talking about this and possible these are not scaled appropriately.

**Comment by karimnaaji** [comment] 2016-07-13 16:48
Yes there might be some scaling factor weirdness going on here (bounding box not scaled properly) we should run with debug flags on to see them.

**Comment by mjcunningham** [comment] 2016-07-13 16:53
cc @msmollin

**Comment by msmollin** [comment] 2016-07-13 17:01
Would you guys like a version compiled with the debug labels?

**Comment by tallytalwar** [comment] 2016-07-13 17:03
Yes that will be useful. But @karimnaaji mentioned it might be something to do with label rotation angles not being packed properly in the vertex buffer. Debug labels will anyhow be useful. :D

**Comment by mjcunningham** [comment] 2016-07-13 17:43
I'm also on the iOS 10 beta.

**Comment by msmollin** [comment] 2016-07-13 17:47
OK I can do a separate debug app in Hockeyapp for people to install. I can get that setup later today. @tallytalwar / @karimnaaji what's the flag I need to pass to the builds to get debug labels to show up?

**Comment by karimnaaji** [comment] 2016-07-13 18:01
There's no building flag that makes them being visible, you would have to add code that triggers that.

When initializing the view controller (or plugged to a UI button if it's a sample app):
```
Tangram::toggleDebugFlag(Tangram::DebugFlags::labels);
```

**Comment by mjcunningham** [comment] 2016-07-13 18:16
This seems to be iOS 10 specific so let's not invest any energy on it but let's keep it open to keep an eye on it.

**Comment by msmollin** [comment] 2016-07-13 18:41
iOS 9.3:
![ios_9_3](https://cloud.githubusercontent.com/assets/1163880/16815436/d13dda4c-4907-11e6-9b98-189335c78ab9.PNG)

iOS 10:
![ios_10b2](https://cloud.githubusercontent.com/assets/1163880/16815448/df5ee3dc-4907-11e6-89bb-0f5b8f0101be.PNG)

**Comment by blair1618** [comment] 2016-07-13 19:23
@msmollin I'm seeing correct label orientation and collision on an iPhone 5S running iOS 9.3

Can you confirm which device + OS combinations produce this issue?

**Comment by msmollin** [comment] 2016-07-13 19:25
IPhone 6S Plus running ios 9.3.2 and an iPhone 6S running 10 beta 2.

**Comment by blair1618** [comment] 2016-07-13 19:56
I can only imagine that the different GPUs cause some discrepancy in the way orientation is packed into the label vertices - would that make any sense @karimnaaji?

**Comment by karimnaaji** [comment] 2016-07-13 20:29
Yes that's what I think is happening, some debugging on a real device would be helpful to understand more this issue.

**Comment by karimnaaji** [comment] 2016-07-14 21:44
@msmollin can you try that with latest tangram version, we're not doing the label rotation in the GPU anymore so this issue might be fixed.

**Comment by blair1618** [comment] 2016-08-03 20:40
*ping!* @msmollin when you get a chance can you try to reproduce this issue with the latest tangram-es code?

**Comment by msmollin** [comment] 2016-08-03 21:12
Sure can. I'll also try it against the ios 10 beta to make sure nothing changes between them.

**Comment by msmollin** [comment] 2016-08-04 20:09
Still appears to be occuring at least on iOS 10 developer beta 4, running on a 6S Plus. Let me know what other details I can provide. 
![screen shot 2016-08-04 at 4 06 09 pm](https://cloud.githubusercontent.com/assets/1163880/17416778/d4aa96ae-5a5d-11e6-8a36-ab88dfe6153d.png)

**Comment by msmollin** [comment] 2016-08-04 20:11
Deleted that last comment - failed to notice which branch I was on. Trying again - standby!

**Comment by tallytalwar** [comment] 2016-09-15 14:27
@msmollin IOS updates resolved this for us?

**Comment by msmollin** [comment] 2016-09-16 00:26
Not the betas exactly. It seems better in later versions on tangram though. I'll compile a new version tomorrow and take a look

**Comment by karimnaaji** [comment] 2016-10-13 16:06
What's the state of this issue on iPhone 6S?

**Comment by msmollin** [comment] 2016-10-13 16:46
Seems to be working fine on both my models. @mjcunningham can you still reproduce this?

**Comment by karimnaaji** [comment] 2016-10-13 16:48
👍  closing this until it shows up again.

**Closed by karimnaaji** 2016-10-13 16:48 UTC
