### ISSUE TITLE
Android cache

### ISSUE THREAD

**Issue by ivangorelow** [tangrams/tangram-es#1309] opened 2017-02-22 11:23 UTC
How can I use cache on android?

**Comment by matteblair** [comment] 2017-02-22 16:10
@ivangorelow Hello again! With the Android library you can use HTTP caching by creating an `HttpHandler` object with a file cache and then giving that handler to the `MapController` with `setHttpHandler`. An example of this is in our demo application: https://github.com/tangrams/tangram-es/blob/master/platforms/android/demo/src/main/java/com/mapzen/tangram/android/MainActivity.java#L84-L114

Does this answer your question?

**Comment by ivangorelow** [comment] 2017-02-27 07:28
and is it possible to load map localy?

**Comment by tallytalwar** [comment] 2017-03-02 00:28
Yes we added support for `mbtiles` in #1015. You will need to have the tile set in a [`mbtiles`](https://github.com/mapbox/mbtiles-spec) format.

Setting the scene file using the following syntax, you should be able to load the map using your `mbtiles` file.

```
sources:
    _savedTiles: #This is an example MBTiles data source.
        type: TopoJSON #We expect TopoJSON data from the source.
        url: /path/to/my/file.mbtiles #Only absolute file paths supported for now.
        max_zoom: 16 #Other optional parameters are applied as usual.
```

Let us know if this works for you.

**Comment by ivangorelow** [comment] 2017-03-02 13:00
no, it doesn't workt

I have error `ERROR mbtilesDataSource.cpp:246: Unable to open SQLite database:`

**Comment by tallytalwar** [comment] 2017-03-02 13:07
Thanks @ivangorelow 

Can you share the MBTiles file you are trying to open?

Thanks

**Comment by ivangorelow** [comment] 2017-03-02 13:11
@tallytalwar  https://openmaptiles.os.zhdk.cloud.switch.ch/v3.3/extracts/moscow_russia.mbtiles

**Comment by tallytalwar** [comment] 2017-03-02 20:40
Ok looks like we need to do resolve android asset path for sqlite database construction, which is not being done at present.

@ivangorelow what path are you putting the mbtiles file in? Are you bundling with the asset?

**Comment by JinYongwHwa** [comment] 2017-03-03 06:53
I try offline tangram map by mbtiles

this is my scene file
```
sources:
    pinonmap:
        type: TopoJSON #GeoJSON, MVT, TopoJSON
        url: file:///storage/emulated/0/test/seoul.mbtiles
        max_zoom: 16
```

this is my test mbtiles file (1-10 zoom level seoul )
[seoul.zip](https://github.com/tangrams/tangram-es/files/815984/seoul.zip)

i have error too

mbtilesDataSource.cpp:246: Unable to open SQLite database: file:///storage/emulated/0/test/seoul4.mbtiles - unable to open database file


p.s
@matteblair Thank you very much to make this wonderful map

**Comment by ivangorelow** [comment] 2017-03-03 09:14
@tallytalwar I try to bundle with asset. I try to do it with full path

**Comment by tallytalwar** [comment] 2017-03-03 11:48
Yup,  was just confirming. I was able to reproduce this behavior. Will update when I have more information on this. 

Thanks again for the report.

**Comment by matteblair** [comment] 2017-03-05 21:25
@JinYongwHwa @ivangorelow File access on Android can be a little complicated. Currently we can only load MBTiles files that are _not_ in the asset bundle for your application (because asset bundles are zip archives and not directories). You'll need to put your MBTiles file in your device storage and use the path to that file as the `url`, like `/storage/emulated/0/test/seoul.mbtiles` from the example above (I believe the `file://` scheme isn't used here). Finally, you need to make sure that your application has the correct permissions to read the file, most likely the [READ_EXTERNAL_STORAGE](https://developer.android.com/reference/android/Manifest.permission.html#READ_EXTERNAL_STORAGE) permission.

It's also possible that there's another problem, but try these steps first and let us know if you succeed!

**Comment by JinYongwHwa** [comment] 2017-03-06 01:39
@matteblair thanks for your answer

I change schema
```
sources:
    pinonmap:
        type: TopoJSON #GeoJSON, MVT, TopoJSON
        url: /storage/emulated/0/test/seoul.mbtiles
        max_zoom: 16
``` 

then i find this error log 
```
ERROR mbtilesDataSource.cpp:246: Unable to open SQLite database: asset:///storage/emulated/0/test/seoul.mbtiles - unable to open database file
```

**Comment by matteblair** [comment] 2017-03-06 05:26
Oh I see the problem now, there's a bug in our implementation. 

When a URL in a scene is resolved, it uses the location of the scene file as the base URL. This means that if the URL isn't absolute (i.e. doesn't start with a scheme like 'file' or 'http') then it is treated as relative to the scene file, which itself has the 'asset' scheme. 

We can fix this by using only the 'path' portion of the URL when accessing an MBTiles file. 

The only work-around I can think of for right now is to put your scene file in device storage with the MBTiles file. Then URLs from the scene wouldn't get resolved as assets. I haven't tested this and it's clearly not a very practical solution, but fixing the root cause should be simple and fast!

**Comment by ivangorelow** [comment] 2017-03-06 10:03
@matteblair thank you for attention. But could you show working example?

**Comment by matteblair** [comment] 2017-03-06 15:55
@ivangorelow We can provide a working example once we fix this bug in our implementation of this on Android.

**Comment by tallytalwar** [comment] 2017-03-10 22:57
#1360 addressed this issue. Closing.

**Closed by tallytalwar** 2017-03-10 22:57 UTC

**Comment by ivangorelow** [comment] 2017-03-20 09:08
in new version I have the same problem


`sources:
    mapzen:
        type: TopoJSON
        #url: https://172.20.255.161:8091/all/{z}/{x}/{y}.topojson
        url: file:///storage/emulated/0/moscow_russia.mbtiles
        max_zoom: 16`

> TANGRAM mbtilesDataSource.cpp:251: SQLite database opened: /storage/emulated/0/moscow_russia.mbtiles

**Comment by tallytalwar** [comment] 2017-03-20 14:36
Hey @ivangorelow 

The message says It did open the sqlite database this time, unlike previously:

>ERROR mbtilesDataSource.cpp:246: Unable to open SQLite database: asset:///storage/emulated/0/test/seoul.mbtiles - unable to open database file

Are you seeing other symptoms or error messages which show the map is not working? And can you also give the complete log output for our reference.

Thanks

Thanks

**Comment by ivangorelow** [comment] 2017-03-20 14:56
`03-20 17:54:45.034 16531-17607/com.impulsm.mobileclientcodd D/Tangram: ERROR topoJsonSource.cpp:25: Json parsing failed on tile [2476/1281/12]: Invalid value. (0)
03-20 17:54:45.191 16531-17606/com.impulsm.mobileclientcodd D/Tangram: ERROR topoJsonSource.cpp:25: Json parsing failed on tile [2475/1281/12]: Invalid value. (0)
03-20 17:54:45.213 16531-17606/com.impulsm.mobileclientcodd D/Tangram: ERROR topoJsonSource.cpp:25: Json parsing failed on tile [2476/1282/12]: Invalid value. (0)
03-20 17:54:45.229 16531-17607/com.impulsm.mobileclientcodd D/Tangram: ERROR topoJsonSource.cpp:25: Json parsing failed on tile [2475/1282/12]: Invalid value. (0)
03-20 17:54:45.268 16531-17607/com.impulsm.mobileclientcodd D/Tangram: ERROR topoJsonSource.cpp:25: Json parsing failed on tile [2476/1280/12]: Invalid value. (0)
03-20 17:54:45.298 16531-17607/com.impulsm.mobileclientcodd D/Tangram: ERROR topoJsonSource.cpp:25: Json parsing failed on tile [2475/1280/12]: Invalid value. (0)
03-20 17:54:45.313 16531-17606/com.impulsm.mobileclientcodd D/Tangram: ERROR topoJsonSource.cpp:25: Json parsing failed on tile [2477/1281/12]: Invalid value. (0)
03-20 17:54:45.325 16531-17607/com.impulsm.mobileclientcodd D/Tangram: ERROR topoJsonSource.cpp:25: Json parsing failed on tile [2474/1281/12]: Invalid value. (0)
03-20 17:54:45.337 16531-17607/com.impulsm.mobileclientcodd D/Tangram: ERROR topoJsonSource.cpp:25: Json parsing failed on tile [2477/1282/12]: Invalid value. (0)
03-20 17:54:45.351 16531-17607/com.impulsm.mobileclientcodd D/Tangram: ERROR topoJsonSource.cpp:25: Json parsing failed on tile [2474/1282/12]: Invalid value. (0)
03-20 17:54:45.367 16531-17607/com.impulsm.mobileclientcodd D/Tangram: ERROR topoJsonSource.cpp:25: Json parsing failed on tile [2477/1280/12]: Invalid value. (0)
03-20 17:54:45.385 16531-17606/com.impulsm.mobileclientcodd D/Tangram: ERROR topoJsonSource.cpp:25: Json parsing failed on tile [2476/1283/12]: Invalid value. (0)
03-20 17:54:45.408 16531-17607/com.impulsm.mobileclientcodd D/Tangram: ERROR topoJsonSource.cpp:25: Json parsing failed on tile [2474/1280/12]: Invalid value. (0)
03-20 17:54:45.419 16531-17606/com.impulsm.mobileclientcodd D/Tangram: ERROR topoJsonSource.cpp:25: Json parsing failed on tile [2475/1283/12]: Invalid value. (0)
03-20 17:54:45.667 16531-17606/com.impulsm.mobileclientcodd D/Tangram: ERROR topoJsonSource.cpp:25: Json parsing failed on tile [2476/1279/12]: Invalid value. (0)
03-20 17:54:45.716 16531-17606/com.impulsm.mobileclientcodd D/Tangram: ERROR topoJsonSource.cpp:25: Json parsing failed on tile [2475/1279/12]: Invalid value. (0)
03-20 17:54:45.727 16531-17607/com.impulsm.mobileclientcodd D/Tangram: ERROR topoJsonSource.cpp:25: Json parsing failed on tile [2477/1283/12]: Invalid value. (0)
03-20 17:54:45.740 16531-17606/com.impulsm.mobileclientcodd D/Tangram: ERROR topoJsonSource.cpp:25: Json parsing failed on tile [2474/1283/12]: Invalid value. (0)
03-20 17:54:45.752 16531-17606/com.impulsm.mobileclientcodd D/Tangram: ERROR topoJsonSource.cpp:25: Json parsing failed on tile [2477/1279/12]: Invalid value. (0)
03-20 17:54:45.762 16531-17607/com.impulsm.mobileclientcodd D/Tangram: ERROR topoJsonSource.cpp:25: Json parsing failed on tile [2474/1279/12]: Invalid value. (0)
03-20 17:54:45.773 16531-17606/com.impulsm.mobileclientcodd D/Tangram: ERROR topoJsonSource.cpp:25: Json parsing failed on tile [2476/1284/12]: Invalid value. (0)
03-20 17:54:45.784 16531-17607/com.impulsm.mobileclientcodd D/Tangram: ERROR topoJsonSource.cpp:25: Json parsing failed on tile [2475/1284/12]: Invalid value. (0)
03-20 17:54:45.793 16531-17606/com.impulsm.mobileclientcodd D/Tangram: ERROR topoJsonSource.cpp:25: Json parsing failed on tile [2477/1284/12]: Invalid value. (0)
03-20 17:54:45.805 16531-17607/com.impulsm.mobileclientcodd D/Tangram: ERROR topoJsonSource.cpp:25: Json parsing failed on tile [2474/1284/12]: Invalid value. (0)
03-20 17:55:07.445 16531-17608/com.impulsm.mobileclientcodd D/Tangram: WARNING mbtilesDataSource.cpp:159: loaded tile: 1238/640/11, 184098
03-20 17:55:07.452 16531-17608/com.impulsm.mobileclientcodd D/Tangram: WARNING mbtilesDataSource.cpp:159: loaded tile: 1237/640/11, 186289
03-20 17:55:07.461 16531-17608/com.impulsm.mobileclientcodd D/Tangram: WARNING mbtilesDataSource.cpp:159: loaded tile: 1238/641/11, 99447
03-20 17:55:07.467 16531-17608/com.impulsm.mobileclientcodd D/Tangram: WARNING mbtilesDataSource.cpp:159: loaded tile: 1237/641/11, 100556
03-20 17:55:07.469 16531-17607/com.impulsm.mobileclientcodd D/Tangram: ERROR topoJsonSource.cpp:25: Json parsing failed on tile [1238/640/11]: Invalid value. (0)
03-20 17:55:07.475 16531-17608/com.impulsm.mobileclientcodd D/Tangram: WARNING mbtilesDataSource.cpp:159: loaded tile: 1238/639/11, 139517
03-20 17:55:07.483 16531-17608/com.impulsm.mobileclientcodd D/Tangram: WARNING mbtilesDataSource.cpp:159: loaded tile: 1237/639/11, 159923
03-20 17:55:07.489 16531-17608/com.impulsm.mobileclientcodd D/Tangram: WARNING mbtilesDataSource.cpp:159: loaded tile: 1238/642/11, 61884
03-20 17:55:07.493 16531-17608/com.impulsm.mobileclientcodd D/Tangram: WARNING mbtilesDataSource.cpp:159: loaded tile: 1237/642/11, 79505
03-20 17:55:07.496 16531-17607/com.impulsm.mobileclientcodd D/Tangram: ERROR topoJsonSource.cpp:25: Json parsing failed on tile [1238/641/11]: Invalid value. (0)
03-20 17:55:07.498 16531-17608/com.impulsm.mobileclientcodd D/Tangram: WARNING mbtilesDataSource.cpp:159: loaded tile: 1239/640/11, 113658
03-20 17:55:07.501 16531-17608/com.impulsm.mobileclientcodd D/Tangram: WARNING mbtilesDataSource.cpp:159: loaded tile: 1239/641/11, 68610
03-20 17:55:07.504 16531-17608/com.impulsm.mobileclientcodd D/Tangram: WARNING mbtilesDataSource.cpp:159: loaded tile: 1236/640/11, 85010
03-20 17:55:07.508 16531-17608/com.impulsm.mobileclientcodd D/Tangram: WARNING mbtilesDataSource.cpp:159: loaded tile: 1236/641/11, 76878
03-20 17:55:07.510 16531-17608/com.impulsm.mobileclientcodd D/Tangram: WARNING mbtilesDataSource.cpp:159: loaded tile: 1239/639/11, 65182
03-20 17:55:07.516 16531-17608/com.impulsm.mobileclientcodd D/Tangram: WARNING mbtilesDataSource.cpp:159: loaded tile: 1239/642/11, 33525
03-20 17:55:07.520 16531-17608/com.impulsm.mobileclientcodd D/Tangram: WARNING mbtilesDataSource.cpp:159: loaded tile: 1236/639/11, 101983
03-20 17:55:07.523 16531-17608/com.impulsm.mobileclientcodd D/Tangram: WARNING mbtilesDataSource.cpp:159: loaded tile: 1236/642/11, 59419
03-20 17:55:07.526 16531-17608/com.impulsm.mobileclientcodd D/Tangram: WARNING mbtilesDataSource.cpp:159: loaded tile: 1236/640/11, 85010
03-20 17:55:07.529 16531-17608/com.impulsm.mobileclientcodd D/Tangram: WARNING mbtilesDataSource.cpp:159: loaded tile: 1236/641/11, 76878
03-20 17:55:07.532 16531-17608/com.impulsm.mobileclientcodd D/Tangram: WARNING mbtilesDataSource.cpp:159: loaded tile: 1236/639/11, 101983
03-20 17:55:07.534 16531-17607/com.impulsm.mobileclientcodd D/Tangram: ERROR topoJsonSource.cpp:25: Json parsing failed on tile [1237/640/11]: Invalid value. (0)
03-20 17:55:07.534 16531-17608/com.impulsm.mobileclientcodd D/Tangram: WARNING mbtilesDataSource.cpp:159: loaded tile: 1236/642/11, 59419
03-20 17:55:07.539 16531-17608/com.impulsm.mobileclientcodd D/Tangram: WARNING mbtilesDataSource.cpp:159: loaded tile: 1238/638/11, 84229
03-20 17:55:07.543 16531-17608/com.impulsm.mobileclientcodd D/Tangram: WARNING mbtilesDataSource.cpp:159: loaded tile: 1237/638/11, 95309
03-20 17:55:07.548 16531-17608/com.impulsm.mobileclientcodd D/Tangram: WARNING mbtilesDataSource.cpp:159: loaded tile: 1239/638/11, 97755
03-20 17:55:07.551 16531-17607/com.impulsm.mobileclientcodd D/Tangram: ERROR topoJsonSource.cpp:25: Json parsing failed on tile [1237/641/11]: Invalid value. (0)
03-20 17:55:07.553 16531-17608/com.impulsm.mobileclientcodd D/Tangram: WARNING mbtilesDataSource.cpp:159: loaded tile: 1236/638/11, 81935
03-20 17:55:07.555 16531-17608/com.impulsm.mobileclientcodd D/Tangram: WARNING mbtilesDataSource.cpp:159: loaded tile: 1238/643/11, 49087
03-20 17:55:07.558 16531-17608/com.impulsm.mobileclientcodd D/Tangram: WARNING mbtilesDataSource.cpp:159: loaded tile: 1237/643/11, 69344
03-20 17:55:07.560 16531-17608/com.impulsm.mobileclientcodd D/Tangram: WARNING mbtilesDataSource.cpp:159: loaded tile: 1239/643/11, 43878
03-20 17:55:07.562 16531-17608/com.impulsm.mobileclientcodd D/Tangram: WARNING mbtilesDataSource.cpp:159: loaded tile: 1236/643/11, 34445
03-20 17:55:07.575 16531-17608/com.impulsm.mobileclientcodd D/Tangram: WARNING mbtilesDataSource.cpp:159: loaded tile: 619/320/10, 97865
03-20 17:55:07.582 16531-17608/com.impulsm.mobileclientcodd D/Tangram: WARNING mbtilesDataSource.cpp:159: loaded tile: 618/320/10, 107658
03-20 17:55:07.592 16531-17608/com.impulsm.mobileclientcodd D/Tangram: WARNING mbtilesDataSource.cpp:159: loaded tile: 619/319/10, 81320
03-20 17:55:07.595 16531-17608/com.impulsm.mobileclientcodd D/Tangram: WARNING mbtilesDataSource.cpp:159: loaded tile: 619/321/10, 53044
03-20 17:55:07.601 16531-17608/com.impulsm.mobileclientcodd D/Tangram: WARNING mbtilesDataSource.cpp:159: loaded tile: 618/319/10, 96479
03-20 17:55:07.605 16531-17608/com.impulsm.mobileclientcodd D/Tangram: WARNING mbtilesDataSource.cpp:159: loaded tile: 618/321/10, 49635
03-20 17:55:07.609 16531-17608/com.impulsm.mobileclientcodd D/Tangram: WARNING mbtilesDataSource.cpp:159: loaded tile: 620/320/10, 41815
03-20 17:55:07.613 16531-17608/com.impulsm.mobileclientcodd D/Tangram: WARNING mbtilesDataSource.cpp:159: loaded tile: 620/321/10, 33833
03-20 17:55:07.615 16531-17608/com.impulsm.mobileclientcodd D/Tangram: WARNING mbtilesDataSource.cpp:159: loaded tile: 620/319/10, 46049
03-20 17:55:07.618 16531-17606/com.impulsm.mobileclientcodd D/Tangram: ERROR topoJsonSource.cpp:25: Json parsing failed on tile [619/320/10]: Invalid value. (0)
03-20 17:55:07.644 16531-17608/com.impulsm.mobileclientcodd D/Tangram: WARNING mbtilesDataSource.cpp:159: loaded tile: 619/322/10, 26066
03-20 17:55:07.646 16531-17608/com.impulsm.mobileclientcodd D/Tangram: WARNING mbtilesDataSource.cpp:159: loaded tile: 619/318/10, 36917
03-20 17:55:07.649 16531-17608/com.impulsm.mobileclientcodd D/Tangram: WARNING mbtilesDataSource.cpp:159: loaded tile: 618/322/10, 25957
03-20 17:55:07.651 16531-17608/com.impulsm.mobileclientcodd D/Tangram: WARNING mbtilesDataSource.cpp:159: loaded tile: 618/318/10, 39345
03-20 17:55:07.652 16531-17608/com.impulsm.mobileclientcodd D/Tangram: WARNING mbtilesDataSource.cpp:159: loaded tile: 620/322/10, 16529
03-20 17:55:07.656 16531-17608/com.impulsm.mobileclientcodd D/Tangram: WARNING mbtilesDataSource.cpp:159: loaded tile: 620/318/10, 28431
03-20 17:55:07.663 16531-17606/com.impulsm.mobileclientcodd D/Tangram: ERROR topoJsonSource.cpp:25: Json parsing failed on tile [618/320/10]: Invalid value. (0)
03-20 17:55:07.673 16531-17606/com.impulsm.mobileclientcodd D/Tangram: ERROR topoJsonSource.cpp:25: Json parsing failed on tile [619/321/10]: Invalid value. (0)
03-20 17:55:07.691 16531-17606/com.impulsm.mobileclientcodd D/Tangram: ERROR topoJsonSource.cpp:25: Json parsing failed on tile [619/319/10]: Invalid value. (0)
03-20 17:55:07.715 16531-17606/com.impulsm.mobileclientcodd D/Tangram: ERROR topoJsonSource.cpp:25: Json parsing failed on tile [618/321/10]: Invalid value. (0)
03-20 17:55:07.745 16531-17606/com.impulsm.mobileclientcodd D/Tangram: ERROR topoJsonSource.cpp:25: Json parsing failed on tile [620/320/10]: Invalid value. (0)
03-20 17:55:07.749 16531-17606/com.impulsm.mobileclientcodd D/Tangram: ERROR topoJsonSource.cpp:25: Json parsing failed on tile [618/319/10]: Invalid value. (0)
03-20 17:55:07.760 16531-17607/com.impulsm.mobileclientcodd D/Tangram: ERROR topoJsonSource.cpp:25: Json parsing failed on tile [620/321/10]: Invalid value. (0)
03-20 17:55:07.762 16531-17606/com.impulsm.mobileclientcodd D/Tangram: ERROR topoJsonSource.cpp:25: Json parsing failed on tile [620/319/10]: Invalid value. (0)
03-20 17:55:07.780 16531-17606/com.impulsm.mobileclientcodd D/Tangram: ERROR topoJsonSource.cpp:25: Json parsing failed on tile [619/322/10]: Invalid value. (0)
03-20 17:55:07.795 16531-17606/com.impulsm.mobileclientcodd D/Tangram: ERROR topoJsonSource.cpp:25: Json parsing failed on tile [619/318/10]: Invalid value. (0)
03-20 17:55:07.806 16531-17606/com.impulsm.mobileclientcodd D/Tangram: ERROR topoJsonSource.cpp:25: Json parsing failed on tile [618/322/10]: Invalid value. (0)
03-20 17:55:07.819 16531-17606/com.impulsm.mobileclientcodd D/Tangram: ERROR topoJsonSource.cpp:25: Json parsing failed on tile [618/318/10]: Invalid value. (0)
03-20 17:55:07.829 16531-17607/com.impulsm.mobileclientcodd D/Tangram: ERROR topoJsonSource.cpp:25: Json parsing failed on tile [620/322/10]: Invalid value. (0)
03-20 17:55:07.842 16531-17607/com.impulsm.mobileclientcodd D/Tangram: ERROR topoJsonSource.cpp:25: Json parsing failed on tile [620/318/10]: Invalid value. (0)
03-20 17:55:08.362 16531-17606/com.impulsm.mobileclientcodd D/Tangram: ERROR topoJsonSource.cpp:25: Json parsing failed on tile [1239/640/11]: Invalid value. (0)
03-20 17:55:08.370 16531-17607/com.impulsm.mobileclientcodd D/Tangram: ERROR topoJsonSource.cpp:25: Json parsing failed on tile [1238/639/11]: Invalid value. (0)
03-20 17:55:08.384 16531-17606/com.impulsm.mobileclientcodd D/Tangram: ERROR topoJsonSource.cpp:25: Json parsing failed on tile [1239/641/11]: Invalid value. (0)
03-20 17:55:08.394 16531-17606/com.impulsm.mobileclientcodd D/Tangram: ERROR topoJsonSource.cpp:25: Json parsing failed on tile [1237/639/11]: Invalid value. (0)
03-20 17:55:08.410 16531-17607/com.impulsm.mobileclientcodd D/Tangram: ERROR topoJsonSource.cpp:25: Json parsing failed on tile [1236/640/11]: Invalid value. (0)
03-20 17:55:08.419 16531-17606/com.impulsm.mobileclientcodd D/Tangram: ERROR topoJsonSource.cpp:25: Json parsing failed on tile [1238/642/11]: Invalid value. (0)
03-20 17:55:08.427 16531-17607/com.impulsm.mobileclientcodd D/Tangram: ERROR topoJsonSource.cpp:25: Json parsing failed on tile [1236/641/11]: Invalid value. (0)
03-20 17:55:08.435 16531-17606/com.impulsm.mobileclientcodd D/Tangram: ERROR topoJsonSource.cpp:25: Json parsing failed on tile [1237/642/11]: Invalid value. (0)
03-20 17:55:08.447 16531-17607/com.impulsm.mobileclientcodd D/Tangram: ERROR topoJsonSource.cpp:25: Json parsing failed on tile [1239/639/11]: Invalid value. (0)
03-20 17:55:08.456 16531-17606/com.impulsm.mobileclientcodd D/Tangram: ERROR topoJsonSource.cpp:25: Json parsing failed on tile [1236/639/11]: Invalid value. (0)
03-20 17:55:08.464 16531-17607/com.impulsm.mobileclientcodd D/Tangram: ERROR topoJsonSource.cpp:25: Json parsing failed on tile [1239/642/11]: Invalid value. (0)
03-20 17:55:08.472 16531-17606/com.impulsm.mobileclientcodd D/Tangram: ERROR topoJsonSource.cpp:25: Json parsing failed on tile [1236/642/11]: Invalid value. (0)
03-20 17:55:08.481 16531-17607/com.impulsm.mobileclientcodd D/Tangram: ERROR topoJsonSource.cpp:25: Json parsing failed on tile [1238/638/11]: Invalid value. (0)
03-20 17:55:08.488 16531-17606/com.impulsm.mobileclientcodd D/Tangram: ERROR topoJsonSource.cpp:25: Json parsing failed on tile [1237/638/11]: Invalid value. (0)
03-20 17:55:08.497 16531-17607/com.impulsm.mobileclientcodd D/Tangram: ERROR topoJsonSource.cpp:25: Json parsing failed on tile [1239/638/11]: Invalid value. (0)
03-20 17:55:08.504 16531-17606/com.impulsm.mobileclientcodd D/Tangram: ERROR topoJsonSource.cpp:25: Json parsing failed on tile [1236/638/11]: Invalid value. (0)
03-20 17:55:08.752 16531-17608/com.impulsm.mobileclientcodd D/Tangram: WARNING mbtilesDataSource.cpp:159: loaded tile: 2475/1278/12, 121049
03-20 17:55:08.757 16531-17608/com.impulsm.mobileclientcodd D/Tangram: WARNING mbtilesDataSource.cpp:159: loaded tile: 2476/1278/12, 128111
03-20 17:55:08.764 16531-17608/com.impulsm.mobileclientcodd D/Tangram: WARNING mbtilesDataSource.cpp:159: loaded tile: 2474/1278/12, 128283
03-20 17:55:08.766 16531-17608/com.impulsm.mobileclientcodd D/Tangram: WARNING mbtilesDataSource.cpp:159: loaded tile: 2477/1278/12, 22703
`

**Comment by tallytalwar** [comment] 2017-03-20 15:19
From the logs it looks like now it can successfully read the mbtiles to a sqlite databse, but unable to parse the tiles inside the database. Can you make sure the tile data in mbtiles is conforming to `topojson` standard, since that is what is being specified in the scene file. And if it is not supposed to be `topojson` then change to an appropriate type via the `source`:`type` in the scene file.

Also for turther debugging can you provide us with the `mbtiles` file you are using in your example above?

**Comment by ivangorelow** [comment] 2017-03-20 15:59
@tallytalwar  https://openmaptiles.os.zhdk.cloud.switch.ch/v3.3/extracts/moscow_russia.mbtiles



this is my scene file

> sources:

    mapzen:
        type: TopoJSON
        #url: https://172.20.255.161:8091/all/{z}/{x}/{y}.topojson
        url: file:///storage/emulated/0/moscow_russia.mbtiles
        max_zoom: 16

**Comment by tallytalwar** [comment] 2017-03-20 16:27
Ahh so it looks like the internal format of the tiles within this mbtiles file you send is MVT.

I can get a map to render by changing `type` to `MVT` instead of `TopoJSON`. Give this a shot and let me know if this works.

Thanks

**Comment by ivangorelow** [comment] 2017-03-20 16:33
@tallytalwar I change it, and now i don't any mistakes, but my map doesn't renders whith cinnabar style.

Do you know any resources where I can take mbtiles?

**Comment by tallytalwar** [comment] 2017-03-20 16:48
@ivangorelow Yup, the data properties in mbtiles files you get from  https://openmaptiles.org are different than what we provide with our tiles. So the same scene files wont work.

We have some work in our pipeline to provide offline mbtiles or zip tile packs, but nothing available right now. If you have to use mbtiles from `openmaptiles` then you have to re-write the scene file using the properties used in the respective mbtiles you are using.

We can see if you can use some of our work to build your own mbtiles with our tile sets.

**Comment by ivangorelow** [comment] 2017-03-20 16:52
and could you give your tile sets?

**Comment by tallytalwar** [comment] 2017-03-20 17:27
We do not have a service where you can get our tile sets, as I said its work in progress.

**Comment by ivangorelow** [comment] 2017-04-07 11:22
@tallytalwar 

why this map doesn't work?( https://yadi.sk/d/XFZ-q4Kr3GkHBw )

**Comment by tallytalwar** [comment] 2017-04-28 21:18
@ivangorelow whats the corresponding scene file you are using with the above mentioned mbtiles dataset?
