### ISSUE TITLE
Unable to rotate, move, pick marker or set map's position

### ISSUE THREAD

**Issue by nasmuris** [tangrams/tangram-es#1922] opened 2018-11-01 05:46 UTC
Hi guys, I've tried new unreleased features from master and encountered several bugs
**TO REPRODUCE THE ISSUE, FOLLOW THESE STEPS:**
A) set RotateResponder or PanResponder and override corresponding methods (just leave them returning false, so according to documentation it's not consumed)
B) implement MarkerPickListener and its methods, set markers (styling string contains interactive:true)
C) set map position with MapController.updateCameraPosition(CameraUpdateFactory.setPosition())

**RESULT:**
A) Unable to rotate or move map
B) onMarkerPick is called, markerPickResult is always null (x,y coords seems to be a bit off also, clicking ~middle top of the screens I've sometimes received values like 0,0)
C) map position does not update
**EXPECTED RESULT:**

A) Map is rotated or moved according to rotate/pan gesture
B) Marker gets recognized
C) Map position is updated

**ENVIRONMENT:**

 - Android 8
 - Moto Z Play 

**OTHER:**
A) I understand that now we can handle region changes with MapChangeListener so this might be kind of feature, not bug in fact
B) onFeaturePick is working OK, not sure how onLabelPick behaves now
C) using CameraUpdateFactory.setZoom() works fine

**Comment by matteblair** [comment] 2018-11-01 21:01
Hi @nasmuris thanks for trying out the latest Tangram! Let me see if I can address each of these items individually:

A) Did you forward the touch input data to the touch responders from `MapController` like the documentation describes? This is a change from the way touch responders previously behaved. https://github.com/tangrams/tangram-es/blob/master/platforms/android/tangram/src/main/java/com/mapzen/tangram/MapController.java#L768-L783

B) `MarkerPickListener` receives a `onMarkerPick` callback for each call to `MapController$pickMarker` whether or not a Marker was picked. If no Marker was picked at the requested point, then the `MarkerPickResult` is `null` and the position coordinates are `0, 0`. Does this describe the behavior you're seeing? (I've realized thanks to this issue that our documentation for `MarkerPickListener` could be clearer, that's good to know)

C) `updateCameraPosition` seems to be working for me. Can you give more details about the parameters you're using and the context in which you're making the call?

**Comment by nasmuris** [comment] 2018-11-02 09:31
Thanks @matteblair for quick response, I'm trying the updateCameraPosition now, seems the problem was calling setZoom() and setPosition() separately, which did cancel the first call,             updateCameraPosition(CameraUpdateFactory.newLngLatZoom()); works OK

**Comment by nasmuris** [comment] 2018-11-02 10:16
@matteblair Calling corresponding methods from mapController gesture responder works too, thanks.
As for the onMarkerPick, I'm still getting `markerPickResult: null` while position is e.g. `300, 400` if clicked on marker, if not, the position is `0, 0`. 
If I debug markerPickCallback, it receives some pretty high markerId (e.g. `4650467992562302976`), while mapController contains only 15 markers I've added with highest markerId `16`

**Comment by nasmuris** [comment] 2018-11-06 11:56
@matteblair did you have some time to check it already? I was trying to workaround this by comparing location from retrieved position with locations of my markers, but it's a bit different and looping through all of the markers might take a lot of time...

**Comment by matteblair** [comment] 2018-11-07 18:39
I tried to reproduce this behavior with the same Marker configuration, but I'm not seeing the issues you're describing :\

**Comment by nasmuris** [comment] 2018-11-08 11:00
@matteblair perhaps you can take a look at fragment of my implementation and help me solve this problem? Thanks in advance 


    public class MapViewManager extends SimpleViewManager<MapView>
        implements MapController.SceneLoadListener, TouchInput.TapResponder,
        TouchInput.DoubleTapResponder, TouchInput.LongPressResponder, FeaturePickListener, LabelPickListener, MarkerPickListener,
        LocationListener, SensorEventListener, TouchInput.RotateResponder, TouchInput.PanResponder, MapView.MapReadyCallback {
    
    private MapController map;
    private MapView mapView;

    private int order = 2100;
    private ArrayList<Marker> mapMarkers = new ArrayList<>();

    @Override
    protected MapView createViewInstance(ThemedReactContext reactContext) {
        cacheDir = reactContext.getExternalCacheDir();
        handler = new Handler();

        final MapView mapView = new MapView(reactContext);
        final MapViewManager _this = this;
        
        //TODO: For MapView to work correctly, your Activity must call the matching methods on MapView for lifecycle events, including onCreate(), onResume(), onPause(), onDestroy(), and onLowMemory().
        LifecycleEventListener lifecycleEventListener = new LifecycleEventListener() {
            @Override
            public void onHostResume() {
                mapView.onResume();
            }

            @Override
            public void onHostPause() {
                mapView.onPause();
            }

            @Override
            public void onHostDestroy() {
                mapView.onDestroy();
            }
        };
        reactContext.addLifecycleEventListener(lifecycleEventListener);
        mapView.getMapAsync(this, getHttpHandler());
        this.mapView = mapView;
        return mapView;
    }

    private ThemedReactContext getContext() {
        return (ThemedReactContext) mapView.getContext();
    }


    @Override
    public void onMapReady(@Nullable MapController newMap) {
        if (newMap.equals(map)) {
            return;
        }
        map = newMap;
        map.loadSceneFile(sceneFile, sceneUpdates);

        map.updateCameraPosition(CameraUpdateFactory.newLngLatZoom(initialLocation, initialZoom));

        TouchInput touchInput = map.getTouchInput();
        touchInput.setTapResponder(this);
        map.setFeaturePickListener(this);
        map.setLabelPickListener(this);
        map.setMarkerPickListener(this);

        map.setMapChangeListener(new MapChangeListener() {
            @Override
            public void onViewComplete() {
                Log.d(LOG_TAG, "View complete");
            }

            @Override
            public void onRegionWillChange(boolean b) {

            }

            @Override
            public void onRegionIsChanging() {
                float zoom = map.getCameraPosition().getZoom();
            }

            @Override
            public void onRegionDidChange(boolean b) {

            }
        });

        resetMarkers();

        relayout();
    }


    @Override
    public void onDropViewInstance(MapView view) {
        super.onDropViewInstance(view);
        view.onDestroy();
    }

    @ReactProp(name = "markers")
    public void resetMarkers(MapView view, ReadableArray markers) {
        this.markers = MarkerDto.Parse(markers);
        resetMarkers();
    }

    public void resetMarkers() {
        if (map == null) return;
        for (Marker mapMarker : mapMarkers) {
            map.removeMarker(mapMarker.getMarkerId());
        }
        mapMarkers.clear();
        int markersOrder = order;
        for (MarkerDto m : this.markers) {
            markersOrder--;
            Marker marker = map.addMarker();
            marker.setStylingFromString("{ style: 'sg-icons', sprite: '" + m.icon + "', size: " + m.iconSize + "px, collide: false, interactive: " + m.isClickable + " }");
            marker.setDrawOrder(markersOrder);
            marker.setPoint(m.location);
            marker.setUserData(m.userData);
            mapMarkers.add(marker);
        }
    }

    @Override
    public void onMarkerPick(MarkerPickResult markerPickResult, float positionX, float positionY) {

        if (markerPickResult == null) {
            Log.d(LOG_TAG, "Empty marker selection");
            return;
        }

        Marker marker = markerPickResult.getMarker();
        Log.d(LOG_TAG, "Picked marker: " + marker.getMarkerId());
    }
    
    @Override
    public boolean onSingleTapConfirmed(float x, float y) {
        map.pickFeature(x, y);
        map.pickLabel(x, y);
        map.pickMarker(x, y);
        return false;
    }
    }

MarkerDto:
`public class MarkerDto {
        public MarkerDto(String id, String name, LngLat location, boolean isClickable, String icon, ReadableMap userData, LngLat focusPoint, int iconSize) {
            this.id = id;
            this.name = name;
            this.location = location;
            this.isClickable = isClickable;
            this.icon = icon;
            this.userData = userData;
            this.focusPoint = focusPoint;
            this.iconSize = iconSize;
        }
    }`

**Comment by Buthrakaur** [comment] 2018-11-15 21:44
@matteblair could you please share commit and preferably also the AAR you tested? I had to compile on my own using a fork from https://github.com/tangrams/tangram-es/commit/9ca833d0689d41c6978dcb9d57b28300eb9ab8f8 and custom CircleCI configuration to get the AAR for non-release version (https://github.com/Buthrakaur/tangram-es) and I maybe did something wrong, because it looks like there could be some numeric overflow error in the `markerId` in native code:
![image](https://user-images.githubusercontent.com/126757/48583380-4119b400-e927-11e8-8b81-98fca1552fea.png)

Also could you please save resulting artifacts for each (even non-release) build on CircleCI so as it's easy to test the pre-release versions? I wasn't able to compile locally on windows machine so had to use my own CircleCI..

**Comment by Buthrakaur** [comment] 2018-11-16 07:34
@matteblair I just found out the build artifacts are on jfrog 🤦‍♂️ 😄  So I tried latest available AAR (https://oss.jfrog.org/artifactory/libs-snapshot/com/mapzen/tangram/tangram/0.9.7-SNAPSHOT/tangram-0.9.7-20181115.180421-67.aar), but same problem - the marker I click on isn't propagated into MarkerPickListener.

**Comment by tallytalwar** [comment] 2019-12-05 20:42
Resolved by #2116

**Closed by tallytalwar** 2019-12-05 20:42 UTC
